"""QG-SEC upload fuzz (plan §9.2 "Gate QG-SEC", §10.2; T3.1).

The corpus is generated by ``scripts/security/make_upload_fuzz.py`` into a temporary directory
(never stored). Every case goes through the Node route's transport rules (mirrored with the
shared helpers of ``edit_v2.assets``) and the real ``edit_v2.assets`` ingest: 100 % must be
rejected (4xx) or safely normalised (2xx) within the time cap, and nothing may map to a 5xx.
The HTTP half of the gate runs the same corpus against ``next start`` (the script's ``http``
command; evidence in ``docs/editor/evidence/W3/``).
"""

from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
import sys
import uuid
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "security" / "make_upload_fuzz.py"


def _load():
    spec = importlib.util.spec_from_file_location("make_upload_fuzz", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


fuzz = _load()


@pytest.fixture(scope="module")
def corpus(tmp_path_factory, edit_v2_ffmpeg) -> tuple[Path, dict]:
    directory = tmp_path_factory.mktemp("upload-fuzz")
    return directory, fuzz.build_corpus(directory, ffmpeg=edit_v2_ffmpeg)


def test_the_corpus_covers_every_row_of_the_plan(corpus):
    _directory, index = corpus
    ids = {case["id"] for case in index["cases"]}
    assert {
        "png_truncated_half", "png_bad_crc", "jpeg_truncated", "jpeg_garbage", "webp_huge_vp8x",
        "m4a_truncated", "wav_truncated", "png_zip_polyglot", "mp4_html_polyglot", "svg_as_png",
        "png_bomb_header", "jpeg_huge_sof", "mp3_ten_hours_silent", "mp3_ten_hours_lying_xing",
        "mkv_external_refs", "hls_as_mp4", "ffconcat_as_mp3", "mp4_external_dref",
        "name_traversal", "name_control", "gif_as_png", "heic_as_png", "pdf_as_png",
        "font_as_png", "zip_as_webp", "empty_logo", "oversize_logo", "oversize_music",
    } <= ids
    assert len(ids) == len(index["cases"]) >= 55
    for case in index["cases"]:
        assert case["expect"] in ("reject", "normalise", "either")
        assert case["kind"] in ("logo", "music")


def test_the_corpus_is_generated_not_stored():
    vcs = shutil.which("git")
    if vcs is None or not (ROOT / ".git").exists():  # e.g. the suite inside the pinned image
        pytest.skip("git or the repository metadata is not available here")
    tracked = subprocess.run([vcs, "ls-files", "scripts/security"], cwd=ROOT,
                             capture_output=True, text=True, check=False).stdout.split()
    assert tracked, "scripts/security is tracked"
    assert all(name.endswith(".py") for name in tracked), tracked


def test_every_case_is_rejected_or_normalised_within_its_cap(corpus, tmp_path):
    directory, _index = corpus
    results = fuzz.run_ingest(directory, jobs_root=tmp_path / "jobs", job_id=str(uuid.uuid4()))
    report = fuzz.summarise(results)
    failed = [item for item in results if not item["pass"]]
    assert not failed, json.dumps(failed, indent=1)
    assert report["serverErrors"] == 0
    assert report["pass"] and report["cases"] == len(results)
    assert report["normalised"] >= 10 and report["rejected"] >= 30
    by_id = {item["id"]: item for item in results}
    assert by_id["mp3_ten_hours_silent"]["reason"] == "duration"
    assert by_id["mp3_ten_hours_lying_xing"]["reason"] == "duration"
    assert by_id["png_bomb_header"]["reason"] == "dimensions"
    for case_id in ("png_truncated_half", "png_zero_width", "webp_garbage"):  # unreadable, not large
        assert by_id[case_id]["reason"] != "dimensions", by_id[case_id]
    assert by_id["svg_as_png"]["status"] == 415 and by_id["svg_as_png"]["stage"] == "transport"
    assert by_id["oversize_music"]["status"] == 413


def test_the_verdict_fails_a_server_error_a_slow_case_and_a_surviving_payload():
    case = {"id": "x", "kind": "logo", "mime": "image/png", "bytes": 1, "expect": "either"}
    assert fuzz.verdict(case, status=500, elapsed_ms=1, code=None, stage="http")["pass"] is False
    assert fuzz.verdict(case, status=422, elapsed_ms=20_001, code=None, stage="http")["pass"] is False
    assert fuzz.verdict(case, status=201, elapsed_ms=1, code=None, stage="http",
                        stored=b"\x89PNG....PK\x03\x04")["pass"] is False
    assert fuzz.verdict(case, status=201, elapsed_ms=1, code=None, stage="http",
                        stored=b"\x89PNG")["pass"] is True
    assert fuzz.verdict({**case, "expect": "reject"}, status=201, elapsed_ms=1, code=None,
                        stage="http")["pass"] is False
    for name in ("../../etc/passwd", "a\\b", "..", "x" * 81):
        assert fuzz.verdict(case, status=201, elapsed_ms=1, code=None, stage="http",
                            name=name)["pass"] is False
    assert fuzz.verdict(case, status=201, elapsed_ms=1, code=None, stage="http",
                        name="passwd")["pass"] is True


# Ingest timing (plan §11.3 T3.1: p95 ≤ 2 s per image, ≤ 8 s per 5-minute track).


def test_the_percentile_is_nearest_rank():
    assert fuzz.percentile([5], 0.95) == 5
    assert fuzz.percentile([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 0.95) == 10
    assert fuzz.percentile([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 0.50) == 5
    assert fuzz.percentile(list(range(1, 21)), 0.95) == 19
    with pytest.raises(ValueError):
        fuzz.percentile([], 0.95)


def test_the_timing_report_pools_the_samples_of_each_class():
    runs = [
        {"input": "PNG a", "kind": "logo", "class": "image", "samplesMs": [100, 200, 300]},
        {"input": "JPEG b", "kind": "logo", "class": "image", "samplesMs": [1900, 2500]},
        {"input": "MP3 5 min", "kind": "music", "class": "track5min", "samplesMs": [5000, 6000]},
    ]
    report = fuzz.timing_report(runs)
    assert report["image"] == {"samples": 5, "p50Ms": 300, "p95Ms": 2500, "maxMs": 2500,
                               "limitMs": 2000, "pass": False}
    assert report["track5min"]["p95Ms"] == 6000 and report["track5min"]["pass"] is True
    assert report["pass"] is False
    assert report["inputs"][0]["p95Ms"] == 300
    fast = fuzz.timing_report([{**runs[0]}, {**runs[2]}])
    assert fast["pass"] is True
    assert fuzz.timing_report([runs[0]])["pass"] is False  # a class without samples never passes


def test_the_timing_inputs_cover_every_format(tmp_path, edit_v2_ffmpeg):
    inputs = fuzz.build_timing_inputs(tmp_path, ffmpeg=edit_v2_ffmpeg, track_seconds=3)
    kinds = {(item["kind"], item["mime"]) for item in inputs}
    assert ("logo", "image/png") in kinds and ("logo", "image/jpeg") in kinds
    assert ("music", "audio/wav") in kinds and ("music", "audio/flac") in kinds
    assert ("music", "audio/mp4") in kinds
    for item in inputs:
        data = (tmp_path / item["file"]).read_bytes()
        assert 0 < len(data) <= (10 << 20 if item["kind"] == "logo" else 50 << 20)
        assert item["class"] == ("image" if item["kind"] == "logo" else "track5min")
    oriented = [item for item in inputs if item["mime"] == "image/jpeg" and "EXIF" in item["input"]]
    assert oriented, "one JPEG carries an EXIF orientation"


# The child-environment audit (E11): wrappers record every child's /proc/self/environ.


def test_a_recorder_logs_the_environment_and_runs_the_real_tool(tmp_path):
    log = tmp_path / "environ.jsonl"
    real = tmp_path / "real.sh"
    real.write_text("#!/bin/sh\necho ran \"$@\"\n")
    real.chmod(0o755)
    wrapper = tmp_path / "tool"
    wrapper.write_text(fuzz.recorder_script(real=str(real), tool="ffmpeg", log=str(log),
                                            interpreter=sys.executable))
    wrapper.chmod(0o755)
    out = subprocess.run([str(wrapper), "-version"], capture_output=True, text=True, check=True,
                         env={"PATH": "/usr/bin:/bin", "OPENROUTER_API_KEY": "planted-x"}).stdout
    assert out.strip() == "ran -version"
    record = json.loads(log.read_text().splitlines()[0])
    assert record["tool"] == "ffmpeg"
    assert record["env"]["OPENROUTER_API_KEY"] == "planted-x"


def test_the_environment_audit_flags_names_outside_the_allowlist_and_planted_values():
    allow = {"python": {"PATH", "HOME", "JOBS_ROOT"}, "ffmpeg": {"PATH", "HOME"}}
    clean = [{"tool": "python", "env": {"PATH": "/bin", "JOBS_ROOT": "/j"}},
             {"tool": "ffmpeg", "env": {"PATH": "/bin", "HOME": "/w"}}]
    report = fuzz.audit_environ(clean, allow=allow, marker="planted-")
    assert report["children"] == 2 and report["byTool"] == {"ffmpeg": 1, "python": 1}
    assert report["namesOutsideAllowlist"] == [] and report["plantedValuesFound"] == 0
    assert report["pass"] is True
    dirty = clean + [{"tool": "ffmpeg", "env": {"PATH": "/bin", "APP_PASSWORD": "planted-pw"}},
                     {"tool": "python", "env": {"PATH": "/bin:planted-in-path"}}]
    report = fuzz.audit_environ(dirty, allow=allow, marker="planted-")
    assert report["namesOutsideAllowlist"] == [{"tool": "ffmpeg", "name": "APP_PASSWORD"}]
    assert report["plantedValuesFound"] == 2 and report["pass"] is False
    assert "planted" not in json.dumps(report["namesOutsideAllowlist"])  # names, never values
    assert fuzz.audit_environ([], allow=allow, marker="planted-")["pass"] is False


def test_the_audit_reads_the_python_allowlist_from_python_cli():
    names = fuzz.child_env_allowlist()
    assert {"PATH", "HOME", "JOBS_ROOT", "POTONGIN_EDITOR_UPLOADS"} <= set(names)
    assert not [name for name in names if name.endswith("_API_KEY")
                or name.startswith(("APP_", "POTONGIN_SETTINGS", "POTONGIN_LLM"))]
