"""QG-SEC upload fuzz (plan §9.2 "Gate QG-SEC", §10.2; T3.1).

The corpus is generated by ``scripts/security/make_upload_fuzz.py`` into a temporary directory
(never stored). Every case goes through the Node route's transport rules (mirrored with the
shared helpers of ``edit_v2.assets``) and the real ``edit_v2.assets`` ingest: 100 % must be
rejected (4xx) or safely normalised (2xx) within the time cap, and nothing may map to a 5xx.
The HTTP half of the gate runs the same corpus against ``next start`` (the script's ``http``
command; evidence in ``docs/editor/evidence/W3/``).
"""

from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
import sys
import uuid
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "security" / "make_upload_fuzz.py"


def _load():
    spec = importlib.util.spec_from_file_location("make_upload_fuzz", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


fuzz = _load()


@pytest.fixture(scope="module")
def corpus(tmp_path_factory, edit_v2_ffmpeg) -> tuple[Path, dict]:
    directory = tmp_path_factory.mktemp("upload-fuzz")
    return directory, fuzz.build_corpus(directory, ffmpeg=edit_v2_ffmpeg)


def test_the_corpus_covers_every_row_of_the_plan(corpus):
    _directory, index = corpus
    ids = {case["id"] for case in index["cases"]}
    assert {
        "png_truncated_half", "png_bad_crc", "jpeg_truncated", "jpeg_garbage", "webp_huge_vp8x",
        "m4a_truncated", "wav_truncated", "png_zip_polyglot", "mp4_html_polyglot", "svg_as_png",
        "png_bomb_header", "jpeg_huge_sof", "mp3_ten_hours_silent", "mp3_ten_hours_lying_xing",
        "mkv_external_refs", "hls_as_mp4", "ffconcat_as_mp3", "mp4_external_dref",
        "name_traversal", "name_control", "gif_as_png", "heic_as_png", "pdf_as_png",
        "font_as_png", "zip_as_webp", "empty_logo", "oversize_logo", "oversize_music",
    } <= ids
    assert len(ids) == len(index["cases"]) >= 55
    for case in index["cases"]:
        assert case["expect"] in ("reject", "normalise", "either")
        assert case["kind"] in ("logo", "music")


def test_the_corpus_is_generated_not_stored():
    vcs = shutil.which("git")
    if vcs is None or not (ROOT / ".git").exists():  # e.g. the suite inside the pinned image
        pytest.skip("git or the repository metadata is not available here")
    tracked = subprocess.run([vcs, "ls-files", "scripts/security"], cwd=ROOT,
                             capture_output=True, text=True, check=False).stdout.split()
    assert tracked, "scripts/security is tracked"
    assert all(name.endswith(".py") for name in tracked), tracked


def test_every_case_is_rejected_or_normalised_within_its_cap(corpus, tmp_path):
    directory, _index = corpus
    results = fuzz.run_ingest(directory, jobs_root=tmp_path / "jobs", job_id=str(uuid.uuid4()))
    report = fuzz.summarise(results)
    failed = [item for item in results if not item["pass"]]
    assert not failed, json.dumps(failed, indent=1)
    assert report["serverErrors"] == 0
    assert report["pass"] and report["cases"] == len(results)
    assert report["normalised"] >= 10 and report["rejected"] >= 30
    by_id = {item["id"]: item for item in results}
    assert by_id["mp3_ten_hours_silent"]["reason"] == "duration"
    assert by_id["mp3_ten_hours_lying_xing"]["reason"] == "duration"
    assert by_id["png_bomb_header"]["reason"] == "dimensions"
    for case_id in ("png_truncated_half", "png_zero_width", "webp_garbage"):  # unreadable, not large
        assert by_id[case_id]["reason"] != "dimensions", by_id[case_id]
    assert by_id["svg_as_png"]["status"] == 415 and by_id["svg_as_png"]["stage"] == "transport"
    assert by_id["oversize_music"]["status"] == 413


def test_the_verdict_fails_a_server_error_a_slow_case_and_a_surviving_payload():
    case = {"id": "x", "kind": "logo", "mime": "image/png", "bytes": 1, "expect": "either"}
    assert fuzz.verdict(case, status=500, elapsed_ms=1, code=None, stage="http")["pass"] is False
    assert fuzz.verdict(case, status=422, elapsed_ms=20_001, code=None, stage="http")["pass"] is False
    assert fuzz.verdict(case, status=201, elapsed_ms=1, code=None, stage="http",
                        stored=b"\x89PNG....PK\x03\x04")["pass"] is False
    assert fuzz.verdict(case, status=201, elapsed_ms=1, code=None, stage="http",
                        stored=b"\x89PNG")["pass"] is True
    assert fuzz.verdict({**case, "expect": "reject"}, status=201, elapsed_ms=1, code=None,
                        stage="http")["pass"] is False
    for name in ("../../etc/passwd", "a\\b", "..", "x" * 81):
        assert fuzz.verdict(case, status=201, elapsed_ms=1, code=None, stage="http",
                            name=name)["pass"] is False
    assert fuzz.verdict(case, status=201, elapsed_ms=1, code=None, stage="http",
                        name="passwd")["pass"] is True
