"""QG-SEC upload fuzz corpus for the Editor V3 asset store (plan §9.2, §10.2; T3.1).

The corpus is generated by this script and never stored in the repository: truncated and
malformed PNG/JPEG/WebP/MP3/M4A/WAV/Ogg/FLAC, PNG+ZIP and MP4+HTML polyglots, an SVG renamed
``.png``, decompression-bomb headers, a 10 h silent MP3 (plain and with a lying Xing header),
Matroska with external references, an HLS playlist renamed ``.mp4``, an FFmpeg concat script,
an MP4 with an external data reference, path-traversal and control-character names, and the
transport limits (empty body, one byte over the cap, a type that does not match the kind).

Gate: **100 %** of the cases are rejected (4xx) or safely normalised (2xx) within their time
cap (image 20 s, audio 60 s), and **no** case produces a 5xx.

Usage (stdlib only; FFmpeg is used to make the valid bases):

    python scripts/security/make_upload_fuzz.py write OUT_DIR
    python scripts/security/make_upload_fuzz.py ingest OUT_DIR EVIDENCE.json
        # every case through the Node transport rules and ``edit_v2.assets`` in-process
    python scripts/security/make_upload_fuzz.py http OUT_DIR EVIDENCE.json --base URL --job ID
        # every case as a real POST /api/jobs/:id/assets; APP_USERNAME / APP_PASSWORD from the
        # environment log in first (a disposable test server, never the owner's app)
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
import platform
import random
import shutil
import struct
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid
import zipfile
import zlib
from collections.abc import Callable, Iterable
from dataclasses import asdict, dataclass
from pathlib import Path

SCHEMA = "potongin.upload-fuzz/1"
PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"
MARKERS = (b"PK\x03\x04", b"<script", b"<html", b"/etc/passwd")
TIME_CAPS_MS = {"logo": 20_000, "music": 60_000}


@dataclass(frozen=True)
class Case:
    id: str
    file: str
    kind: str  # X-Asset-Kind
    mime: str  # Content-Type
    expect: str  # "reject" | "normalise" | "either"
    name: str | None = None  # X-Asset-Name before percent-encoding (None: header omitted)
    note: str = ""


# --- media helpers -------------------------------------------------------------------------------


def _ffmpeg(ffmpeg: str, *args: str) -> None:
    subprocess.run([ffmpeg, "-nostdin", "-hide_banner", "-loglevel", "error", "-y",
                    "-threads", "2", *args], check=True, timeout=300,
                   stdin=subprocess.DEVNULL)


def _has_encoder(ffmpeg: str, name: str) -> bool:
    out = subprocess.run([ffmpeg, "-hide_banner", "-encoders"], capture_output=True, text=True,
                         check=False).stdout
    return any(line.split()[1:2] == [name] for line in out.splitlines())


def _chunk(kind: bytes, body: bytes) -> bytes:
    return struct.pack(">I", len(body)) + kind + body + struct.pack(
        ">I", zlib.crc32(kind + body) & 0xFFFFFFFF)


def _png_chunks(data: bytes) -> list[tuple[bytes, bytes]]:
    out, position = [], 8
    while position + 12 <= len(data):
        (length,) = struct.unpack(">I", data[position:position + 4])
        out.append((data[position + 4:position + 8], data[position + 8:position + 8 + length]))
        position += 12 + length
    return out


def _png(chunks: Iterable[tuple[bytes, bytes]]) -> bytes:
    return PNG_SIGNATURE + b"".join(_chunk(kind, body) for kind, body in chunks)


def _ihdr(width: int, height: int, depth: int = 8, colour: int = 6) -> bytes:
    return struct.pack(">IIBBBBB", width, height, depth, colour, 0, 0, 0)


def png_bomb_header() -> bytes:
    """IHDR claims 100 000 × 100 000 RGBA (40 GB decoded) over a tiny IDAT."""
    return _png([(b"IHDR", _ihdr(100_000, 100_000)), (b"IDAT", zlib.compress(b"\x00" * 1024)),
                 (b"IEND", b"")])


def png_deflate_bomb() -> bytes:
    """A real 4096 × 4096 RGBA image of zeros: 64 MiB decoded from ~65 KB (within the caps)."""
    row = b"\x00" * (1 + 4096 * 4)
    compressor = zlib.compressobj(9)
    body = b"".join(compressor.compress(row) for _ in range(4096)) + compressor.flush()
    return _png([(b"IHDR", _ihdr(4096, 4096)), (b"IDAT", body), (b"IEND", b"")])


def png_zero_width(base: bytes) -> bytes:
    chunks = _png_chunks(base)
    body = bytearray(chunks[0][1])
    body[0:4] = b"\x00\x00\x00\x00"
    return _png([(b"IHDR", bytes(body)), *chunks[1:]])


def png_bad_crc(base: bytes) -> bytes:
    data = bytearray(base)
    at = data.index(b"IDAT") + 10
    data[at] ^= 0xFF
    return bytes(data)


def png_apng(base: bytes) -> bytes:
    chunks = _png_chunks(base)
    ihdr = chunks[0][1]
    width, height = struct.unpack(">II", ihdr[:8])
    idat = b"".join(body for kind, body in chunks if kind == b"IDAT")

    def fctl(seq: int) -> bytes:
        return struct.pack(">IIIIIHHBB", seq, width, height, 0, 0, 1, 10, 0, 0)

    return _png([(b"IHDR", ihdr), (b"acTL", struct.pack(">II", 2, 0)), (b"fcTL", fctl(0)),
                 (b"IDAT", idat), (b"fcTL", fctl(1)), (b"fdAT", struct.pack(">I", 2) + idat),
                 (b"IEND", b"")])


def png_text_chunks(base: bytes) -> bytes:
    chunks = _png_chunks(base)
    script = b"<html><script>fetch('/api/jobs')</script></html>"
    extra = [(b"tEXt", b"Comment\x00" + script * 200),
             (b"iTXt", b"XML:com.adobe.xmp\x00\x00\x00\x00\x00" + script),
             (b"zTXt", b"Title\x00\x00" + zlib.compress(script * 1000))]
    return _png([chunks[0], *extra, *chunks[1:]])


def png_zip_polyglot(base: bytes) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr("index.html", "<html><script>alert(document.cookie)</script></html>")
    return base + buffer.getvalue()


def jpeg_huge_sof() -> bytes:
    sof = b"\xff\xc0" + struct.pack(">HBHHB", 17, 8, 65000, 65000, 3) + \
        b"\x01\x22\x00\x02\x11\x01\x03\x11\x01"
    return b"\xff\xd8" + sof + b"\xff\xda\x00\x0c\x03\x01\x00\x02\x11\x03\x11\x00\x3f\x00" + \
        bytes(512) + b"\xff\xd9"


def jpeg_exif_bomb(base: bytes) -> bytes:
    """An APP1 whose IFD claims 65 535 entries and points past its end (bounded parsing)."""
    tiff = b"II*\x00" + struct.pack("<I", 8) + struct.pack("<H", 0xFFFF) + \
        struct.pack("<HHII", 0x0112, 3, 0xFFFFFFFF, 0x7FFFFFF0) * 4
    payload = b"Exif\x00\x00" + tiff
    return base[:2] + b"\xff\xe1" + struct.pack(">H", len(payload) + 2) + payload + base[2:]


def jpeg_garbage() -> bytes:
    return b"\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00" + \
        random.Random(7).randbytes(20_000)


def webp_huge_vp8x() -> bytes:
    body = b"\x10\x00\x00\x00" + (16383).to_bytes(3, "little") + (16383).to_bytes(3, "little")
    chunk = b"VP8X" + struct.pack("<I", len(body)) + body
    alph = b"VP8L" + struct.pack("<I", 5) + b"\x2f\xff\x3f\xff\x0f" + b"\x00"
    payload = b"WEBP" + chunk + alph
    return b"RIFF" + struct.pack("<I", len(payload)) + payload


MP3_SILENT_FRAME = b"\xff\xe3\x18\xc4" + bytes(68)  # MPEG-2.5 layer III, 8 kbps, 8 kHz, mono


def mp3_ten_hours(*, lying_xing: bool) -> bytes:
    """10 h of silent 72-byte frames (500 000 × 576 samples at 8 kHz) = 36 MB."""
    frames = 500_000
    first = MP3_SILENT_FRAME
    if lying_xing:  # claims 833 frames (60 s): only the decode cap can catch the real length
        tag = b"Xing" + struct.pack(">II", 1, 833)
        first = first[:13] + tag + first[13 + len(tag):]
    return first + MP3_SILENT_FRAME * (frames - 1)


def mp3_huge_id3(base: bytes) -> bytes:
    size = 20 << 20
    syncsafe = bytes([(size >> 21) & 0x7F, (size >> 14) & 0x7F, (size >> 7) & 0x7F, size & 0x7F])
    return b"ID3\x04\x00\x00" + syncsafe + bytes(size) + base


def _boxes(data: bytes) -> list[tuple[bytes, bytes]]:
    out, position = [], 0
    while position + 8 <= len(data):
        (size,) = struct.unpack(">I", data[position:position + 4])
        kind = data[position + 4:position + 8]
        if size < 8 or position + size > len(data):
            raise ValueError("not a simple box tree")
        out.append((kind, data[position + 8:position + size]))
        position += size
    return out


def _box(kind: bytes, body: bytes) -> bytes:
    return struct.pack(">I", len(body) + 8) + kind + body


_CONTAINERS = {b"moov", b"trak", b"mdia", b"minf", b"dinf"}


def _patch_dref(data: bytes) -> bytes:
    out = []
    for kind, body in _boxes(data):
        if kind == b"dref":
            location = b"file:///etc/passwd\x00"
            entry = _box(b"url ", b"\x00\x00\x00\x00" + location)  # flags 0: external data
            body = body[:4] + struct.pack(">I", 1) + entry
        elif kind in _CONTAINERS:
            body = _patch_dref(body)
        out.append(_box(kind, body))
    return b"".join(out)


def mp4_external_dref(base: bytes) -> bytes:
    """The 'url ' data reference of the audio track made external (``-enable_drefs 0``)."""
    return _patch_dref(base)


def mp4_html_polyglot(base: bytes) -> bytes:
    html = b"<!DOCTYPE html><html><body><script>alert(document.cookie)</script></body></html>"
    return base + _box(b"free", html * 10)


def mkv_external_refs() -> bytes:
    ebml = bytes.fromhex("1a45dfa3") + b"\xa3" + bytes.fromhex("4282") + b"\x88matroska" + \
        bytes.fromhex("42870104") + bytes.fromhex("42850102")
    # Segment → Info → SegmentFilename/NextFilename pointing at other files (linked segments).
    info = bytes.fromhex("3b8375") + b"\x8b/etc/passwd" + bytes.fromhex("3e83bb") + b"\x87../x.mkv"
    segment = bytes.fromhex("18538067") + b"\x01\x00\x00\x00\x00\x00\x00\x40" + \
        bytes.fromhex("1549a966") + bytes([0x80 | len(info)]) + info
    return ebml + segment + bytes(64)


def wav_bad_fmt() -> bytes:
    fmt = struct.pack("<HHIIHH", 1, 0, 0, 0, 0, 16)
    data = bytes(4000)
    body = b"WAVE" + b"fmt " + struct.pack("<I", len(fmt)) + fmt + b"data" + \
        struct.pack("<I", len(data)) + data
    return b"RIFF" + struct.pack("<I", len(body)) + body


def wav_channels(channels: int, seconds: float = 1.0, rate: int = 8000) -> bytes:
    frames = int(seconds * rate)
    fmt = struct.pack("<HHIIHH", 1, channels, rate, rate * channels * 2, channels * 2, 16)
    data = bytes(frames * channels * 2)
    body = b"WAVE" + b"fmt " + struct.pack("<I", len(fmt)) + fmt + b"data" + \
        struct.pack("<I", len(data)) + data
    return b"RIFF" + struct.pack("<I", len(body)) + body


def _svg() -> bytes:
    return (b"<?xml version=\"1.0\"?><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"64\" "
            b"height=\"64\" onload=\"alert(1)\"><image href=\"file:///etc/passwd\"/></svg>")


def _gif() -> bytes:
    return (b"GIF89a\x01\x00\x01\x00\x80\x00\x00\x00\x00\x00\xff\xff\xff!\xf9\x04\x01\x00\x00\x00"
            b"\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;")


def _heic() -> bytes:
    return _box(b"ftyp", b"heic\x00\x00\x00\x00mif1heic") + _box(b"meta", bytes(64))


def _zip() -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr("a.txt", "x" * 100)
    return buffer.getvalue()


# --- the corpus --------------------------------------------------------------------------------------


def _bases(ffmpeg: str, work: Path) -> dict[str, bytes | None]:
    bases: dict[str, bytes | None] = {}
    _ffmpeg(ffmpeg, "-f", "lavfi", "-i", "testsrc2=s=200x150,format=rgba", "-frames:v", "1",
            str(work / "base.png"))
    _ffmpeg(ffmpeg, "-f", "lavfi", "-i", "testsrc2=s=200x150", "-frames:v", "1", "-q:v", "3",
            str(work / "base.jpg"))
    bases["png"] = (work / "base.png").read_bytes()
    bases["jpeg"] = (work / "base.jpg").read_bytes()
    bases["webp"] = None
    if _has_encoder(ffmpeg, "libwebp"):
        _ffmpeg(ffmpeg, "-f", "lavfi", "-i", "testsrc2=s=200x150", "-frames:v", "1", "-c:v",
                "libwebp", str(work / "base.webp"))
        bases["webp"] = (work / "base.webp").read_bytes()
    tone = ["-f", "lavfi", "-i", "sine=f=440:d=3:sample_rate=44100", "-ac", "2"]
    _ffmpeg(ffmpeg, *tone, "-c:a", "pcm_s16le", str(work / "base.wav"))
    _ffmpeg(ffmpeg, *tone, "-c:a", "aac", "-b:a", "128k", str(work / "base.m4a"))
    _ffmpeg(ffmpeg, *tone, "-c:a", "flac", str(work / "base.flac"))
    bases["wav"] = (work / "base.wav").read_bytes()
    bases["m4a"] = (work / "base.m4a").read_bytes()
    bases["flac"] = (work / "base.flac").read_bytes()
    bases["mp3"] = None
    if _has_encoder(ffmpeg, "libmp3lame"):
        _ffmpeg(ffmpeg, *tone, "-c:a", "libmp3lame", "-b:a", "128k", str(work / "base.mp3"))
        bases["mp3"] = (work / "base.mp3").read_bytes()
    bases["ogg"] = None
    if _has_encoder(ffmpeg, "libvorbis"):
        _ffmpeg(ffmpeg, *tone, "-c:a", "libvorbis", str(work / "base.ogg"))
        bases["ogg"] = (work / "base.ogg").read_bytes()
    _ffmpeg(ffmpeg, "-f", "lavfi", "-i", "testsrc2=s=160x120:d=2", "-f", "lavfi", "-i",
            "sine=d=2", "-c:v", "mpeg4", "-c:a", "aac", "-shortest", str(work / "video.mp4"))
    bases["video_mp4"] = (work / "video.mp4").read_bytes()
    return bases


def build_corpus(out_dir: Path, *, ffmpeg: str | None = None) -> dict:
    """Write every case into ``out_dir`` and return the index (also ``out_dir/index.json``)."""
    ffmpeg = ffmpeg or shutil.which("ffmpeg")
    if ffmpeg is None:
        raise SystemExit("ffmpeg is required to build the corpus")
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    rng = random.Random(20260928)
    with tempfile.TemporaryDirectory(prefix="upload-fuzz-") as tmp:
        b = _bases(ffmpeg, Path(tmp))
    png, jpeg, wav, m4a, flac = b["png"], b["jpeg"], b["wav"], b["m4a"], b["flac"]
    assert png and jpeg and wav and m4a and flac
    cases: list[tuple[Case, bytes]] = []

    def add(case_id: str, data: bytes, kind: str, mime: str, expect: str, **extra) -> None:
        cases.append((Case(case_id, f"{case_id}.bin", kind, mime, expect, **extra), data))

    # Images.
    add("png_valid", png, "logo", "image/png", "normalise", name="logo.png")
    add("png_truncated_half", png[: len(png) // 2], "logo", "image/png", "either")
    add("png_truncated_header", png[:30], "logo", "image/png", "reject")
    add("png_bad_crc", png_bad_crc(png), "logo", "image/png", "either")
    add("png_zero_width", png_zero_width(png), "logo", "image/png", "reject")
    add("png_bomb_header", png_bomb_header(), "logo", "image/png", "reject",
        note="decompression-bomb header: 100000x100000")
    add("png_deflate_bomb", png_deflate_bomb(), "logo", "image/png", "either",
        note="64 MiB of zeros from ~65 KB, within the 4096x4096 cap")
    add("png_zip_polyglot", png_zip_polyglot(png), "logo", "image/png", "normalise")
    add("png_apng", png_apng(png), "logo", "image/png", "normalise")
    add("png_text_chunks", png_text_chunks(png), "logo", "image/png", "normalise")
    add("png_random_after_signature", PNG_SIGNATURE + rng.randbytes(4000), "logo", "image/png",
        "reject")
    add("svg_as_png", _svg(), "logo", "image/png", "reject")
    add("svg_as_svg", _svg(), "logo", "image/svg+xml", "reject")
    add("gif_as_png", _gif(), "logo", "image/png", "reject")
    add("gif_as_gif", _gif(), "logo", "image/gif", "reject")
    add("heic_as_png", _heic(), "logo", "image/png", "reject")
    add("heic_as_m4a", _heic(), "music", "audio/mp4", "reject")
    add("pdf_as_png", b"%PDF-1.7\n1 0 obj<<>>endobj\n%%EOF\n", "logo", "image/png", "reject")
    add("jpeg_valid", jpeg, "logo", "image/jpeg", "normalise")
    add("jpeg_truncated", jpeg[: len(jpeg) // 2], "logo", "image/jpeg", "either")
    add("jpeg_garbage", jpeg_garbage(), "logo", "image/jpeg", "reject")
    add("jpeg_huge_sof", jpeg_huge_sof(), "logo", "image/jpeg", "reject")
    add("jpeg_exif_bomb", jpeg_exif_bomb(jpeg), "logo", "image/jpeg", "normalise")
    add("png_as_jpeg", png, "logo", "image/jpeg", "reject")
    if b["webp"]:
        add("webp_valid", b["webp"], "logo", "image/webp", "normalise")
        add("webp_truncated", b["webp"][: len(b["webp"]) // 2], "logo", "image/webp", "either")
    add("webp_huge_vp8x", webp_huge_vp8x(), "logo", "image/webp", "reject")
    add("webp_garbage", b"RIFF\x00\x10\x00\x00WEBPVP8 " + rng.randbytes(4000), "logo",
        "image/webp", "reject")
    add("font_as_png", b"OTTO\x00\x0a\x00\x80" + bytes(200), "logo", "image/png", "reject")
    add("zip_as_webp", _zip(), "logo", "image/webp", "reject")
    add("png_as_music", png, "music", "image/png", "reject")
    # Names (the image itself is valid).
    add("name_traversal", png, "logo", "image/png", "normalise", name="../../../../etc/passwd")
    add("name_windows_path", png, "logo", "image/png", "normalise",
        name="C:\\Windows\\System32\\logo.png")
    add("name_control", png, "logo", "image/png", "reject", name="logo\x00.png")
    add("name_newline", png, "logo", "image/png", "reject", name="logo\r\nX-Injected: 1")
    add("name_too_long", png, "logo", "image/png", "reject", name="x" * 81 + ".png")
    # Transport limits.
    add("empty_logo", b"", "logo", "image/png", "reject")
    add("oversize_logo", png + bytes((10 << 20) + 1 - len(png)), "logo", "image/png", "reject")
    # Music.
    add("wav_valid", wav, "music", "audio/wav", "normalise", name="lagu.wav")
    add("wav_truncated", wav[: len(wav) // 3], "music", "audio/wav", "either")
    add("wav_bad_fmt", wav_bad_fmt(), "music", "audio/wav", "reject")
    add("wav_six_channels", wav_channels(6), "music", "audio/wav", "reject")
    add("m4a_valid", m4a, "music", "audio/mp4", "normalise")
    add("m4a_truncated", m4a[: len(m4a) // 2], "music", "audio/mp4", "either")
    add("mp4_html_polyglot", mp4_html_polyglot(m4a), "music", "audio/mp4", "normalise")
    add("mp4_external_dref", mp4_external_dref(m4a), "music", "audio/mp4", "either")
    add("mp4_with_video", b["video_mp4"], "music", "audio/mp4", "reject")
    add("mkv_external_refs", mkv_external_refs(), "music", "audio/mp4", "reject")
    add("hls_as_mp4", b"#EXTM3U\n#EXT-X-TARGETDURATION:10\n#EXTINF:10,\nfile:///etc/passwd\n"
        b"#EXTINF:10,\nhttp://127.0.0.1:1/x.ts\n#EXT-X-ENDLIST\n", "music", "audio/mp4", "reject")
    add("ffconcat_as_mp3", b"ffconcat version 1.0\nfile '/etc/passwd'\nfile 'http://x/y'\n",
        "music", "audio/mpeg", "reject")
    add("mp3_ten_hours_silent", mp3_ten_hours(lying_xing=False), "music", "audio/mpeg", "reject",
        note="10 h of silent frames, no Xing header")
    add("mp3_ten_hours_lying_xing", mp3_ten_hours(lying_xing=True), "music", "audio/mpeg",
        "reject", note="10 h of frames behind a Xing header that claims 60 s")
    add("mp3_garbage_after_sync", b"\xff\xfb\x90\x64" + rng.randbytes(30_000), "music",
        "audio/mpeg", "either")
    if b["mp3"]:
        add("mp3_valid", b["mp3"], "music", "audio/mpeg", "normalise")
        add("mp3_truncated", b["mp3"][: len(b["mp3"]) // 2], "music", "audio/mpeg", "either")
        add("mp3_huge_id3", mp3_huge_id3(b["mp3"]), "music", "audio/mpeg", "either")
        add("mp3_as_wav", b["mp3"], "music", "audio/wav", "reject")
    if b["ogg"]:
        add("ogg_valid", b["ogg"], "music", "audio/ogg", "normalise")
    add("ogg_garbage", b"OggS\x00\x02" + rng.randbytes(8000), "music", "audio/ogg", "reject")
    add("flac_valid", flac, "music", "audio/flac", "normalise")
    add("flac_garbage", b"fLaC" + rng.randbytes(8000), "music", "audio/flac", "reject")
    add("font_as_flac", b"OTTO\x00\x0a\x00\x80" + bytes(200), "music", "audio/flac", "reject")
    add("zip_as_ogg", _zip(), "music", "audio/ogg", "reject")
    add("empty_music", b"", "music", "audio/wav", "reject")
    add("oversize_music", wav + bytes((50 << 20) + 1 - len(wav)), "music", "audio/wav",
        "reject")
    add("music_as_logo_kind", wav, "logo", "audio/wav", "reject")

    index = {"schema": SCHEMA, "cases": []}
    for case, data in cases:
        (out_dir / case.file).write_bytes(data)
        entry = asdict(case)
        entry["bytes"] = len(data)
        entry["sha256"] = hashlib.sha256(data).hexdigest()
        index["cases"].append(entry)
    (out_dir / "index.json").write_text(json.dumps(index, indent=1, ensure_ascii=False) + "\n")
    return index


def load_index(corpus_dir: Path) -> dict:
    return json.loads((Path(corpus_dir) / "index.json").read_text())


# --- verdicts ----------------------------------------------------------------------------------------


def verdict(case: dict, *, status: int, elapsed_ms: int, code: str | None,
            reason: str | None = None, stored: bytes | None = None, name: str | None = None,
            stage: str) -> dict:
    """One case's result: 2xx = normalised, 4xx = rejected, anything else fails the gate."""
    outcome = "normalised" if 200 <= status < 300 else "rejected" if 400 <= status < 500 else \
        "server_error"
    cap = TIME_CAPS_MS.get(case["kind"], 20_000)
    problems = []
    if outcome == "server_error":
        problems.append(f"status {status}")
    if case["expect"] == "normalise" and outcome != "normalised":
        problems.append("expected a normalised asset")
    if case["expect"] == "reject" and outcome != "rejected":
        problems.append("expected a rejection")
    if elapsed_ms > cap:
        problems.append(f"over the {cap} ms cap")
    if stored is not None and any(marker in stored for marker in MARKERS):
        problems.append("a polyglot payload survived normalisation")
    # Display names never carry a path (identical content keeps its first name, so the exact
    # value is checked by the unit tests of both languages, not here).
    if outcome == "normalised" and name is not None and (
            "/" in name or "\\" in name or name in (".", "..") or len(name) > 80):
        problems.append("a display name kept a path or exceeded 80 characters")
    return {"id": case["id"], "kind": case["kind"], "mime": case["mime"], "bytes": case["bytes"],
            "expect": case["expect"], "stage": stage, "status": status, "outcome": outcome,
            "code": code, "reason": reason, "elapsedMs": elapsed_ms, "capMs": cap,
            "pass": not problems, "problems": problems}


def summarise(results: list[dict], **extra) -> dict:
    counts: dict[str, int] = {}
    for item in results:
        counts[item["outcome"]] = counts.get(item["outcome"], 0) + 1
    by_kind = {}
    for kind in ("logo", "music"):
        times = sorted(item["elapsedMs"] for item in results if item["kind"] == kind)
        if times:
            by_kind[kind] = {"cases": len(times), "maxMs": times[-1]}
    return {
        "schema": "potongin.gate/1",
        "gate": "QG-SEC upload fuzz (plan §9.2, §10.2)",
        "task": "T3.1",
        "threshold": "100% rejected (4xx) or safely normalised (2xx) within the time cap "
                     "(image 20 s, audio 60 s); no 5xx",
        "cases": len(results),
        "rejected": counts.get("rejected", 0),
        "normalised": counts.get("normalised", 0),
        "serverErrors": counts.get("server_error", 0),
        "failed": sum(1 for item in results if not item["pass"]),
        "timesByKind": by_kind,
        "pass": all(item["pass"] for item in results) and bool(results),
        "results": results,
        **extra,
    }


# --- Python level: the Node transport rules, then edit_v2.assets ------------------------------------

_EXIT_STATUS = {0: 201, 4: 404, 9: 409}
_CODE_STATUS = {"asset_type_unsupported": 415, "asset_too_large": 413, "asset_rejected": 422,
                "asset_quota_exceeded": 409}


def run_ingest(corpus_dir: Path, *, jobs_root: Path, job_id: str,
               handle: Callable | None = None, only: Iterable[str] | None = None) -> list[dict]:
    """Every case through the transport rules of ``web/lib/asset-upload.mjs`` (mirrored with
    the shared Python helpers) and ``edit_v2.assets.handle`` in-process."""
    from ai_clipper.edit_v2 import assets

    handle = handle or assets.handle
    corpus_dir = Path(corpus_dir)
    job_dir = Path(jobs_root) / job_id
    (job_dir / "analysis").mkdir(parents=True, exist_ok=True)
    wanted = set(only) if only is not None else None
    results = []
    for case in load_index(corpus_dir)["cases"]:
        if wanted is not None and case["id"] not in wanted:
            continue
        data = (corpus_dir / case["file"]).read_bytes()
        started = time.monotonic()
        transport = _transport(assets, case, data)
        if transport is not None:
            status, code = transport
            results.append(verdict(case, status=status, code=code, stage="transport",
                                   elapsed_ms=round((time.monotonic() - started) * 1000)))
            continue
        incoming = job_dir / "analysis" / "assets" / ".incoming"
        incoming.mkdir(parents=True, exist_ok=True, mode=0o700)
        incoming_id = str(uuid.uuid4())
        fd = os.open(incoming / incoming_id, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW,
                     0o600)
        with os.fdopen(fd, "wb") as handle_out:
            handle_out.write(data)
        envelope = {"op": "ingest", "jobId": job_id, "incomingId": incoming_id,
                    "kind": case["kind"], "mime": case["mime"],
                    "name": assets.normalise_name(case["name"]),
                    "idempotencyKey": str(uuid.uuid4())}
        exit_code, payload = handle(json.dumps(envelope).encode(), jobs_root=Path(jobs_root))
        elapsed = round((time.monotonic() - started) * 1000)
        error = payload.get("error") or {}
        status = _EXIT_STATUS.get(exit_code, 500)
        if exit_code == 3:
            status = _CODE_STATUS.get(error.get("code"), 500)
        stored = name = None
        if exit_code == 0:
            asset = payload["asset"]
            suffix = ".png" if asset["kind"] == "logo" else ".m4a"
            stored = (job_dir / "analysis" / "assets" / f"{asset['sha256']}{suffix}").read_bytes()
            name = asset["name"]
        results.append(verdict(case, status=status, code=error.get("code"), reason=error.get("ref"),
                               elapsed_ms=elapsed, stored=stored, name=name, stage="ingest"))
        if (incoming / incoming_id).exists():
            results[-1]["pass"] = False
            results[-1]["problems"].append("the quarantined original survived")
    return results


def _transport(assets, case: dict, data: bytes) -> tuple[int, str] | None:
    """The Node route's own refusals, in its order (web/lib/asset-upload.mjs)."""
    kind, mime = case["kind"], case["mime"]
    if mime not in assets.ALLOWED_TYPES.get(kind, ()):
        return 415, "asset_type_unsupported"
    if len(data) == 0:
        return 400, "invalid_request"
    if len(data) > assets.MAX_UPLOAD_BYTES[kind]:
        return 413, "asset_too_large"
    try:
        assets.normalise_name(case["name"])
    except ValueError:
        return 400, "invalid_request"
    if assets.sniff(data[:64]) != assets.FORMATS[mime]:
        return 415, "asset_type_unsupported"
    return None


# --- HTTP level ----------------------------------------------------------------------------------------


def _login(base: str, username: str, password: str) -> str:
    body = urllib.parse.urlencode({"username": username, "password": password}).encode()
    request = urllib.request.Request(f"{base}/api/auth/login", data=body, method="POST", headers={
        "Content-Type": "application/x-www-form-urlencoded", "Origin": base,
        "Sec-Fetch-Site": "same-origin"})

    class NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *_args, **_kwargs):
            return None

    opener = urllib.request.build_opener(NoRedirect)
    try:
        response = opener.open(request, timeout=30)
        headers = response.headers
    except urllib.error.HTTPError as error:
        headers = error.headers
    for value in headers.get_all("Set-Cookie") or []:
        name, _, rest = value.partition("=")
        if name.strip() == "potongin_session":
            return rest.split(";", 1)[0]
    raise SystemExit("login failed")


def post_case(base: str, job_id: str, token: str, case: dict, data: bytes) -> tuple[int, dict]:
    headers = {"Origin": base, "Sec-Fetch-Site": "same-origin", "Cookie": f"potongin_session={token}",
               "Content-Type": case["mime"], "X-Asset-Kind": case["kind"],
               "Idempotency-Key": str(uuid.uuid4())}
    if case["name"] is not None:
        headers["X-Asset-Name"] = urllib.parse.quote(case["name"], safe="")
    request = urllib.request.Request(f"{base}/api/jobs/{job_id}/assets", data=data, method="POST",
                                     headers=headers)
    try:
        with urllib.request.urlopen(request, timeout=180) as response:
            return response.status, json.loads(response.read() or b"{}")
    except urllib.error.HTTPError as error:
        try:
            return error.code, json.loads(error.read() or b"{}")
        except ValueError:
            return error.code, {}


def fetch(base: str, path: str, token: str) -> bytes:
    request = urllib.request.Request(f"{base}{path}", headers={
        "Cookie": f"potongin_session={token}"})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def run_http(corpus_dir: Path, *, base: str, job_id: str, username: str,
             password: str) -> list[dict]:
    token = _login(base, username, password)
    corpus_dir = Path(corpus_dir)
    results = []
    for case in load_index(corpus_dir)["cases"]:
        data = (corpus_dir / case["file"]).read_bytes()
        started = time.monotonic()
        status, body = post_case(base, job_id, token, case, data)
        elapsed = round((time.monotonic() - started) * 1000)
        stored = None
        if 200 <= status < 300:
            stored = fetch(base, f"/api/jobs/{job_id}/assets/{body['sha256']}", token)
            if hashlib.sha256(stored).hexdigest() != body["sha256"]:
                status = 599  # the served bytes are not the asset: fail the case loudly
        results.append(verdict(case, status=status, code=body.get("code"),
                               reason=body.get("reason"), elapsed_ms=elapsed, stored=stored,
                               name=body.get("name"), stage="http"))
    return results


# --- CLI -------------------------------------------------------------------------------------------


def _toolchain() -> dict:
    ffmpeg = shutil.which("ffmpeg")
    version = "missing"
    if ffmpeg:
        version = subprocess.run([ffmpeg, "-version"], capture_output=True, text=True,
                                 check=False).stdout.split("\n", 1)[0]
    return {"ffmpeg": version, "python": platform.python_version(),
            "machine": platform.machine(), "cpus": os.cpu_count(),
            "load": [round(x, 1) for x in os.getloadavg()]}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    sub = parser.add_subparsers(dest="command", required=True)
    write = sub.add_parser("write")
    write.add_argument("out_dir", type=Path)
    ingest = sub.add_parser("ingest")
    ingest.add_argument("corpus", type=Path)
    ingest.add_argument("evidence", type=Path)
    ingest.add_argument("--jobs-root", type=Path)
    http = sub.add_parser("http")
    http.add_argument("corpus", type=Path)
    http.add_argument("evidence", type=Path)
    http.add_argument("--base", required=True)
    http.add_argument("--job", required=True)
    http.add_argument("--stack", default="")
    args = parser.parse_args(argv)
    if args.command == "write":
        index = build_corpus(args.out_dir)
        print(json.dumps({"cases": len(index["cases"]), "dir": str(args.out_dir)}))
        return 0
    if args.command == "ingest":
        with tempfile.TemporaryDirectory(prefix="upload-fuzz-jobs-") as tmp:
            root = args.jobs_root or Path(tmp)
            results = run_ingest(args.corpus, jobs_root=root, job_id=str(uuid.uuid4()))
        report = summarise(results, level="python (transport rules + edit_v2.assets.handle)",
                           toolchain=_toolchain())
    else:
        username, password = os.environ.get("APP_USERNAME"), os.environ.get("APP_PASSWORD")
        if not username or not password:
            raise SystemExit("APP_USERNAME and APP_PASSWORD of the test server are required")
        results = run_http(args.corpus, base=args.base.rstrip("/"), job_id=args.job,
                           username=username, password=password)
        report = summarise(results, level="http (POST /api/jobs/:id/assets, next start)",
                           stack=args.stack, toolchain=_toolchain())
    args.evidence.parent.mkdir(parents=True, exist_ok=True)
    args.evidence.write_text(json.dumps(report, indent=1, ensure_ascii=False) + "\n")
    print(json.dumps({key: report[key] for key in ("cases", "rejected", "normalised",
                                                     "serverErrors", "failed", "pass")}))
    return 0 if report["pass"] else 1


if __name__ == "__main__":
    sys.exit(main())
