"""Upload gates of the job asset store (plan §9.2, §10.2, §11.3 T3.1): QG-SEC and ingest timing.

The corpus is generated by this script and never stored in the repository: truncated and
malformed PNG/JPEG/WebP/MP3/M4A/WAV/Ogg/FLAC, PNG+ZIP and MP4+HTML polyglots, an SVG renamed
``.png``, decompression-bomb headers, a 10 h silent MP3 (plain and with a lying Xing header),
Matroska with external references, an HLS playlist renamed ``.mp4``, an FFmpeg concat script,
an MP4 with an external data reference, path-traversal and control-character names, and the
transport limits (empty body, one byte over the cap, a type that does not match the kind).

Gate: **100 %** of the cases are rejected (4xx) or safely normalised (2xx) within their time
cap (image 20 s, audio 60 s), and **no** case produces a 5xx.

Usage (stdlib only; FFmpeg is used to make the valid bases):

    python scripts/security/make_upload_fuzz.py write OUT_DIR
    python scripts/security/make_upload_fuzz.py ingest OUT_DIR EVIDENCE.json
        # every case through the Node transport rules and ``edit_v2.assets`` in-process
    python scripts/security/make_upload_fuzz.py http OUT_DIR EVIDENCE.json --base URL --job ID
        # every case as a real POST /api/jobs/:id/assets; APP_USERNAME / APP_PASSWORD from the
        # environment log in first (a disposable test server, never the owner's app)
    python scripts/security/make_upload_fuzz.py matrix EVIDENCE.json --base URL --job ID \\
        [--environ-log LOG --marker TEXT]
        # authentication without the proxy, CSRF, transport headers, a 40 MB body, the serving
        # headers; with --environ-log, the environment of every child the server spawned (E11)
    python scripts/security/make_upload_fuzz.py recorders DIR --log LOG --interpreter PY \\
        --python REAL_PYTHON
        # wrappers (python, ffmpeg, ffprobe) that log their environment, for the server under test
    python scripts/security/make_upload_fuzz.py timing-inputs DIR
    python scripts/security/make_upload_fuzz.py timing DIR EVIDENCE.json
        # ingest p95: <= 2 s per image, <= 8 s per 5-minute track (one process per upload)
"""

from __future__ import annotations

import argparse
import array
import hashlib
import http.client
import io
import json
import math
import os
import platform
import random
import re
import shutil
import struct
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid
import zipfile
import zlib
from collections.abc import Callable, Iterable
from dataclasses import asdict, dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCHEMA = "potongin.upload-fuzz/1"
PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"
MARKERS = (b"PK\x03\x04", b"<script", b"<html", b"/etc/passwd")
TIME_CAPS_MS = {"logo": 20_000, "music": 60_000}


@dataclass(frozen=True)
class Case:
    id: str
    file: str
    kind: str  # X-Asset-Kind
    mime: str  # Content-Type
    expect: str  # "reject" | "normalise" | "either"
    name: str | None = None  # X-Asset-Name before percent-encoding (None: header omitted)
    note: str = ""


# Media helpers.


def _ffmpeg(ffmpeg: str, *args: str) -> None:
    subprocess.run([ffmpeg, "-nostdin", "-hide_banner", "-loglevel", "error", "-y",
                    "-threads", "2", *args], check=True, timeout=300,
                   stdin=subprocess.DEVNULL)


def _has_encoder(ffmpeg: str, name: str) -> bool:
    out = subprocess.run([ffmpeg, "-hide_banner", "-encoders"], capture_output=True, text=True,
                         check=False).stdout
    return any(line.split()[1:2] == [name] for line in out.splitlines())


def _chunk(kind: bytes, body: bytes) -> bytes:
    return struct.pack(">I", len(body)) + kind + body + struct.pack(
        ">I", zlib.crc32(kind + body) & 0xFFFFFFFF)


def _png_chunks(data: bytes) -> list[tuple[bytes, bytes]]:
    out, position = [], 8
    while position + 12 <= len(data):
        (length,) = struct.unpack(">I", data[position:position + 4])
        out.append((data[position + 4:position + 8], data[position + 8:position + 8 + length]))
        position += 12 + length
    return out


def _png(chunks: Iterable[tuple[bytes, bytes]]) -> bytes:
    return PNG_SIGNATURE + b"".join(_chunk(kind, body) for kind, body in chunks)


def _ihdr(width: int, height: int, depth: int = 8, colour: int = 6) -> bytes:
    return struct.pack(">IIBBBBB", width, height, depth, colour, 0, 0, 0)


def png_bomb_header() -> bytes:
    """IHDR claims 100 000 × 100 000 RGBA (40 GB decoded) over a tiny IDAT."""
    return _png([(b"IHDR", _ihdr(100_000, 100_000)), (b"IDAT", zlib.compress(b"\x00" * 1024)),
                 (b"IEND", b"")])


def png_deflate_bomb() -> bytes:
    """A real 4096 × 4096 RGBA image of zeros: 64 MiB decoded from ~65 KB (within the caps)."""
    row = b"\x00" * (1 + 4096 * 4)
    compressor = zlib.compressobj(9)
    body = b"".join(compressor.compress(row) for _ in range(4096)) + compressor.flush()
    return _png([(b"IHDR", _ihdr(4096, 4096)), (b"IDAT", body), (b"IEND", b"")])


def png_zero_width(base: bytes) -> bytes:
    chunks = _png_chunks(base)
    body = bytearray(chunks[0][1])
    body[0:4] = b"\x00\x00\x00\x00"
    return _png([(b"IHDR", bytes(body)), *chunks[1:]])


def png_bad_crc(base: bytes) -> bytes:
    data = bytearray(base)
    at = data.index(b"IDAT") + 10
    data[at] ^= 0xFF
    return bytes(data)


def png_apng(base: bytes) -> bytes:
    chunks = _png_chunks(base)
    ihdr = chunks[0][1]
    width, height = struct.unpack(">II", ihdr[:8])
    idat = b"".join(body for kind, body in chunks if kind == b"IDAT")

    def fctl(seq: int) -> bytes:
        return struct.pack(">IIIIIHHBB", seq, width, height, 0, 0, 1, 10, 0, 0)

    return _png([(b"IHDR", ihdr), (b"acTL", struct.pack(">II", 2, 0)), (b"fcTL", fctl(0)),
                 (b"IDAT", idat), (b"fcTL", fctl(1)), (b"fdAT", struct.pack(">I", 2) + idat),
                 (b"IEND", b"")])


def png_text_chunks(base: bytes) -> bytes:
    chunks = _png_chunks(base)
    script = b"<html><script>fetch('/api/jobs')</script></html>"
    extra = [(b"tEXt", b"Comment\x00" + script * 200),
             (b"iTXt", b"XML:com.adobe.xmp\x00\x00\x00\x00\x00" + script),
             (b"zTXt", b"Title\x00\x00" + zlib.compress(script * 1000))]
    return _png([chunks[0], *extra, *chunks[1:]])


def png_zip_polyglot(base: bytes) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr("index.html", "<html><script>alert(document.cookie)</script></html>")
    return base + buffer.getvalue()


def jpeg_huge_sof() -> bytes:
    sof = b"\xff\xc0" + struct.pack(">HBHHB", 17, 8, 65000, 65000, 3) + \
        b"\x01\x22\x00\x02\x11\x01\x03\x11\x01"
    return b"\xff\xd8" + sof + b"\xff\xda\x00\x0c\x03\x01\x00\x02\x11\x03\x11\x00\x3f\x00" + \
        bytes(512) + b"\xff\xd9"


def jpeg_exif_bomb(base: bytes) -> bytes:
    """An APP1 whose IFD claims 65 535 entries and points past its end (bounded parsing)."""
    tiff = b"II*\x00" + struct.pack("<I", 8) + struct.pack("<H", 0xFFFF) + \
        struct.pack("<HHII", 0x0112, 3, 0xFFFFFFFF, 0x7FFFFFF0) * 4
    payload = b"Exif\x00\x00" + tiff
    return base[:2] + b"\xff\xe1" + struct.pack(">H", len(payload) + 2) + payload + base[2:]


def jpeg_garbage() -> bytes:
    return b"\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00" + \
        random.Random(7).randbytes(20_000)


def webp_huge_vp8x() -> bytes:
    body = b"\x10\x00\x00\x00" + (16383).to_bytes(3, "little") + (16383).to_bytes(3, "little")
    chunk = b"VP8X" + struct.pack("<I", len(body)) + body
    alph = b"VP8L" + struct.pack("<I", 5) + b"\x2f\xff\x3f\xff\x0f" + b"\x00"
    payload = b"WEBP" + chunk + alph
    return b"RIFF" + struct.pack("<I", len(payload)) + payload


MP3_SILENT_FRAME = b"\xff\xe3\x18\xc4" + bytes(68)  # MPEG-2.5 layer III, 8 kbps, 8 kHz, mono


def mp3_ten_hours(*, lying_xing: bool) -> bytes:
    """10 h of silent 72-byte frames (500 000 × 576 samples at 8 kHz) = 36 MB."""
    frames = 500_000
    first = MP3_SILENT_FRAME
    if lying_xing:  # claims 833 frames (60 s): only the decode cap can catch the real length
        tag = b"Xing" + struct.pack(">II", 1, 833)
        first = first[:13] + tag + first[13 + len(tag):]
    return first + MP3_SILENT_FRAME * (frames - 1)


def mp3_huge_id3(base: bytes) -> bytes:
    size = 20 << 20
    syncsafe = bytes([(size >> 21) & 0x7F, (size >> 14) & 0x7F, (size >> 7) & 0x7F, size & 0x7F])
    return b"ID3\x04\x00\x00" + syncsafe + bytes(size) + base


def _boxes(data: bytes) -> list[tuple[bytes, bytes]]:
    out, position = [], 0
    while position + 8 <= len(data):
        (size,) = struct.unpack(">I", data[position:position + 4])
        kind = data[position + 4:position + 8]
        if size < 8 or position + size > len(data):
            raise ValueError("not a simple box tree")
        out.append((kind, data[position + 8:position + size]))
        position += size
    return out


def _box(kind: bytes, body: bytes) -> bytes:
    return struct.pack(">I", len(body) + 8) + kind + body


_CONTAINERS = {b"moov", b"trak", b"mdia", b"minf", b"dinf"}


def _patch_dref(data: bytes) -> bytes:
    out = []
    for kind, body in _boxes(data):
        if kind == b"dref":
            location = b"file:///etc/passwd\x00"
            entry = _box(b"url ", b"\x00\x00\x00\x00" + location)  # flags 0: external data
            body = body[:4] + struct.pack(">I", 1) + entry
        elif kind in _CONTAINERS:
            body = _patch_dref(body)
        out.append(_box(kind, body))
    return b"".join(out)


def mp4_external_dref(base: bytes) -> bytes:
    """The 'url ' data reference of the audio track made external (``-enable_drefs 0``)."""
    return _patch_dref(base)


def mp4_html_polyglot(base: bytes) -> bytes:
    html = b"<!DOCTYPE html><html><body><script>alert(document.cookie)</script></body></html>"
    return base + _box(b"free", html * 10)


def mkv_external_refs() -> bytes:
    ebml = bytes.fromhex("1a45dfa3") + b"\xa3" + bytes.fromhex("4282") + b"\x88matroska" + \
        bytes.fromhex("42870104") + bytes.fromhex("42850102")
    # Segment → Info → SegmentFilename/NextFilename pointing at other files (linked segments).
    info = bytes.fromhex("3b8375") + b"\x8b/etc/passwd" + bytes.fromhex("3e83bb") + b"\x87../x.mkv"
    segment = bytes.fromhex("18538067") + b"\x01\x00\x00\x00\x00\x00\x00\x40" + \
        bytes.fromhex("1549a966") + bytes([0x80 | len(info)]) + info
    return ebml + segment + bytes(64)


def wav_bad_fmt() -> bytes:
    fmt = struct.pack("<HHIIHH", 1, 0, 0, 0, 0, 16)
    data = bytes(4000)
    body = b"WAVE" + b"fmt " + struct.pack("<I", len(fmt)) + fmt + b"data" + \
        struct.pack("<I", len(data)) + data
    return b"RIFF" + struct.pack("<I", len(body)) + body


def wav_channels(channels: int, seconds: float = 1.0, rate: int = 8000) -> bytes:
    frames = int(seconds * rate)
    fmt = struct.pack("<HHIIHH", 1, channels, rate, rate * channels * 2, channels * 2, 16)
    data = bytes(frames * channels * 2)
    body = b"WAVE" + b"fmt " + struct.pack("<I", len(fmt)) + fmt + b"data" + \
        struct.pack("<I", len(data)) + data
    return b"RIFF" + struct.pack("<I", len(body)) + body


def _svg() -> bytes:
    return (b"<?xml version=\"1.0\"?><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"64\" "
            b"height=\"64\" onload=\"alert(1)\"><image href=\"file:///etc/passwd\"/></svg>")


def _gif() -> bytes:
    return (b"GIF89a\x01\x00\x01\x00\x80\x00\x00\x00\x00\x00\xff\xff\xff!\xf9\x04\x01\x00\x00\x00"
            b"\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;")


def _heic() -> bytes:
    return _box(b"ftyp", b"heic\x00\x00\x00\x00mif1heic") + _box(b"meta", bytes(64))


def _zip() -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr("a.txt", "x" * 100)
    return buffer.getvalue()


# The corpus.


def _bases(ffmpeg: str, work: Path) -> dict[str, bytes | None]:
    bases: dict[str, bytes | None] = {}
    _ffmpeg(ffmpeg, "-f", "lavfi", "-i", "testsrc2=s=200x150,format=rgba", "-frames:v", "1",
            str(work / "base.png"))
    _ffmpeg(ffmpeg, "-f", "lavfi", "-i", "testsrc2=s=200x150", "-frames:v", "1", "-q:v", "3",
            str(work / "base.jpg"))
    bases["png"] = (work / "base.png").read_bytes()
    bases["jpeg"] = (work / "base.jpg").read_bytes()
    bases["webp"] = None
    if _has_encoder(ffmpeg, "libwebp"):
        _ffmpeg(ffmpeg, "-f", "lavfi", "-i", "testsrc2=s=200x150", "-frames:v", "1", "-c:v",
                "libwebp", str(work / "base.webp"))
        bases["webp"] = (work / "base.webp").read_bytes()
    tone = ["-f", "lavfi", "-i", "sine=f=440:d=3:sample_rate=44100", "-ac", "2"]
    _ffmpeg(ffmpeg, *tone, "-c:a", "pcm_s16le", str(work / "base.wav"))
    _ffmpeg(ffmpeg, *tone, "-c:a", "aac", "-b:a", "128k", str(work / "base.m4a"))
    _ffmpeg(ffmpeg, *tone, "-c:a", "flac", str(work / "base.flac"))
    bases["wav"] = (work / "base.wav").read_bytes()
    bases["m4a"] = (work / "base.m4a").read_bytes()
    bases["flac"] = (work / "base.flac").read_bytes()
    bases["mp3"] = None
    if _has_encoder(ffmpeg, "libmp3lame"):
        _ffmpeg(ffmpeg, *tone, "-c:a", "libmp3lame", "-b:a", "128k", str(work / "base.mp3"))
        bases["mp3"] = (work / "base.mp3").read_bytes()
    bases["ogg"] = None
    if _has_encoder(ffmpeg, "libvorbis"):
        _ffmpeg(ffmpeg, *tone, "-c:a", "libvorbis", str(work / "base.ogg"))
        bases["ogg"] = (work / "base.ogg").read_bytes()
    _ffmpeg(ffmpeg, "-f", "lavfi", "-i", "testsrc2=s=160x120:d=2", "-f", "lavfi", "-i",
            "sine=d=2", "-c:v", "mpeg4", "-c:a", "aac", "-shortest", str(work / "video.mp4"))
    bases["video_mp4"] = (work / "video.mp4").read_bytes()
    return bases


def build_corpus(out_dir: Path, *, ffmpeg: str | None = None) -> dict:
    """Write every case into ``out_dir`` and return the index (also ``out_dir/index.json``)."""
    ffmpeg = ffmpeg or shutil.which("ffmpeg")
    if ffmpeg is None:
        raise SystemExit("ffmpeg is required to build the corpus")
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    rng = random.Random(20260928)
    with tempfile.TemporaryDirectory(prefix="upload-fuzz-") as tmp:
        b = _bases(ffmpeg, Path(tmp))
    png, jpeg, wav, m4a, flac = b["png"], b["jpeg"], b["wav"], b["m4a"], b["flac"]
    assert png and jpeg and wav and m4a and flac
    cases: list[tuple[Case, bytes]] = []

    def add(case_id: str, data: bytes, kind: str, mime: str, expect: str, **extra) -> None:
        cases.append((Case(case_id, f"{case_id}.bin", kind, mime, expect, **extra), data))

    # Images.
    add("png_valid", png, "logo", "image/png", "normalise", name="logo.png")
    add("png_truncated_half", png[: len(png) // 2], "logo", "image/png", "either")
    add("png_truncated_header", png[:30], "logo", "image/png", "reject")
    add("png_bad_crc", png_bad_crc(png), "logo", "image/png", "either")
    add("png_zero_width", png_zero_width(png), "logo", "image/png", "reject")
    add("png_bomb_header", png_bomb_header(), "logo", "image/png", "reject",
        note="decompression-bomb header: 100000x100000")
    add("png_deflate_bomb", png_deflate_bomb(), "logo", "image/png", "either",
        note="64 MiB of zeros from ~65 KB, within the 4096x4096 cap")
    add("png_zip_polyglot", png_zip_polyglot(png), "logo", "image/png", "normalise")
    add("png_apng", png_apng(png), "logo", "image/png", "normalise")
    add("png_text_chunks", png_text_chunks(png), "logo", "image/png", "normalise")
    add("png_random_after_signature", PNG_SIGNATURE + rng.randbytes(4000), "logo", "image/png",
        "reject")
    add("svg_as_png", _svg(), "logo", "image/png", "reject")
    add("svg_as_svg", _svg(), "logo", "image/svg+xml", "reject")
    add("gif_as_png", _gif(), "logo", "image/png", "reject")
    add("gif_as_gif", _gif(), "logo", "image/gif", "reject")
    add("heic_as_png", _heic(), "logo", "image/png", "reject")
    add("heic_as_m4a", _heic(), "music", "audio/mp4", "reject")
    add("pdf_as_png", b"%PDF-1.7\n1 0 obj<<>>endobj\n%%EOF\n", "logo", "image/png", "reject")
    add("jpeg_valid", jpeg, "logo", "image/jpeg", "normalise")
    add("jpeg_truncated", jpeg[: len(jpeg) // 2], "logo", "image/jpeg", "either")
    add("jpeg_garbage", jpeg_garbage(), "logo", "image/jpeg", "reject")
    add("jpeg_huge_sof", jpeg_huge_sof(), "logo", "image/jpeg", "reject")
    add("jpeg_exif_bomb", jpeg_exif_bomb(jpeg), "logo", "image/jpeg", "normalise")
    add("png_as_jpeg", png, "logo", "image/jpeg", "reject")
    if b["webp"]:
        add("webp_valid", b["webp"], "logo", "image/webp", "normalise")
        add("webp_truncated", b["webp"][: len(b["webp"]) // 2], "logo", "image/webp", "either")
    add("webp_huge_vp8x", webp_huge_vp8x(), "logo", "image/webp", "reject")
    add("webp_garbage", b"RIFF\x00\x10\x00\x00WEBPVP8 " + rng.randbytes(4000), "logo",
        "image/webp", "reject")
    add("font_as_png", b"OTTO\x00\x0a\x00\x80" + bytes(200), "logo", "image/png", "reject")
    add("zip_as_webp", _zip(), "logo", "image/webp", "reject")
    add("png_as_music", png, "music", "image/png", "reject")
    # Names (the image itself is valid).
    add("name_traversal", png, "logo", "image/png", "normalise", name="../../../../etc/passwd")
    add("name_windows_path", png, "logo", "image/png", "normalise",
        name="C:\\Windows\\System32\\logo.png")
    add("name_control", png, "logo", "image/png", "reject", name="logo\x00.png")
    add("name_newline", png, "logo", "image/png", "reject", name="logo\r\nX-Injected: 1")
    add("name_too_long", png, "logo", "image/png", "reject", name="x" * 81 + ".png")
    # Transport limits.
    add("empty_logo", b"", "logo", "image/png", "reject")
    add("oversize_logo", png + bytes((10 << 20) + 1 - len(png)), "logo", "image/png", "reject")
    # Music.
    add("wav_valid", wav, "music", "audio/wav", "normalise", name="lagu.wav")
    add("wav_truncated", wav[: len(wav) // 3], "music", "audio/wav", "either")
    add("wav_bad_fmt", wav_bad_fmt(), "music", "audio/wav", "reject")
    add("wav_six_channels", wav_channels(6), "music", "audio/wav", "reject")
    add("m4a_valid", m4a, "music", "audio/mp4", "normalise")
    add("m4a_truncated", m4a[: len(m4a) // 2], "music", "audio/mp4", "either")
    add("mp4_html_polyglot", mp4_html_polyglot(m4a), "music", "audio/mp4", "normalise")
    add("mp4_external_dref", mp4_external_dref(m4a), "music", "audio/mp4", "either")
    add("mp4_with_video", b["video_mp4"], "music", "audio/mp4", "reject")
    add("mkv_external_refs", mkv_external_refs(), "music", "audio/mp4", "reject")
    add("hls_as_mp4", b"#EXTM3U\n#EXT-X-TARGETDURATION:10\n#EXTINF:10,\nfile:///etc/passwd\n"
        b"#EXTINF:10,\nhttp://127.0.0.1:1/x.ts\n#EXT-X-ENDLIST\n", "music", "audio/mp4", "reject")
    add("ffconcat_as_mp3", b"ffconcat version 1.0\nfile '/etc/passwd'\nfile 'http://x/y'\n",
        "music", "audio/mpeg", "reject")
    add("mp3_ten_hours_silent", mp3_ten_hours(lying_xing=False), "music", "audio/mpeg", "reject",
        note="10 h of silent frames, no Xing header")
    add("mp3_ten_hours_lying_xing", mp3_ten_hours(lying_xing=True), "music", "audio/mpeg",
        "reject", note="10 h of frames behind a Xing header that claims 60 s")
    add("mp3_garbage_after_sync", b"\xff\xfb\x90\x64" + rng.randbytes(30_000), "music",
        "audio/mpeg", "either")
    if b["mp3"]:
        add("mp3_valid", b["mp3"], "music", "audio/mpeg", "normalise")
        add("mp3_truncated", b["mp3"][: len(b["mp3"]) // 2], "music", "audio/mpeg", "either")
        add("mp3_huge_id3", mp3_huge_id3(b["mp3"]), "music", "audio/mpeg", "either")
        add("mp3_as_wav", b["mp3"], "music", "audio/wav", "reject")
    if b["ogg"]:
        add("ogg_valid", b["ogg"], "music", "audio/ogg", "normalise")
    add("ogg_garbage", b"OggS\x00\x02" + rng.randbytes(8000), "music", "audio/ogg", "reject")
    add("flac_valid", flac, "music", "audio/flac", "normalise")
    add("flac_garbage", b"fLaC" + rng.randbytes(8000), "music", "audio/flac", "reject")
    add("font_as_flac", b"OTTO\x00\x0a\x00\x80" + bytes(200), "music", "audio/flac", "reject")
    add("zip_as_ogg", _zip(), "music", "audio/ogg", "reject")
    add("empty_music", b"", "music", "audio/wav", "reject")
    add("oversize_music", wav + bytes((50 << 20) + 1 - len(wav)), "music", "audio/wav",
        "reject")
    add("music_as_logo_kind", wav, "logo", "audio/wav", "reject")

    index = {"schema": SCHEMA, "cases": []}
    for case, data in cases:
        (out_dir / case.file).write_bytes(data)
        entry = asdict(case)
        entry["bytes"] = len(data)
        entry["sha256"] = hashlib.sha256(data).hexdigest()
        index["cases"].append(entry)
    (out_dir / "index.json").write_text(json.dumps(index, indent=1, ensure_ascii=False) + "\n")
    return index


def load_index(corpus_dir: Path) -> dict:
    return json.loads((Path(corpus_dir) / "index.json").read_text())


# Verdicts.


def verdict(case: dict, *, status: int, elapsed_ms: int, code: str | None,
            reason: str | None = None, stored: bytes | None = None, name: str | None = None,
            stage: str) -> dict:
    """One case's result: 2xx = normalised, 4xx = rejected, anything else fails the gate."""
    outcome = "normalised" if 200 <= status < 300 else "rejected" if 400 <= status < 500 else \
        "server_error"
    cap = TIME_CAPS_MS.get(case["kind"], 20_000)
    problems = []
    if outcome == "server_error":
        problems.append(f"status {status}")
    if case["expect"] == "normalise" and outcome != "normalised":
        problems.append("expected a normalised asset")
    if case["expect"] == "reject" and outcome != "rejected":
        problems.append("expected a rejection")
    if elapsed_ms > cap:
        problems.append(f"over the {cap} ms cap")
    if stored is not None and any(marker in stored for marker in MARKERS):
        problems.append("a polyglot payload survived normalisation")
    # Display names never carry a path (identical content keeps its first name, so the exact
    # value is checked by the unit tests of both languages, not here).
    if outcome == "normalised" and name is not None and (
            "/" in name or "\\" in name or name in (".", "..") or len(name) > 80):
        problems.append("a display name kept a path or exceeded 80 characters")
    return {"id": case["id"], "kind": case["kind"], "mime": case["mime"], "bytes": case["bytes"],
            "expect": case["expect"], "stage": stage, "status": status, "outcome": outcome,
            "code": code, "reason": reason, "elapsedMs": elapsed_ms, "capMs": cap,
            "pass": not problems, "problems": problems}


def summarise(results: list[dict], **extra) -> dict:
    counts: dict[str, int] = {}
    for item in results:
        counts[item["outcome"]] = counts.get(item["outcome"], 0) + 1
    by_kind = {}
    for kind in ("logo", "music"):
        times = sorted(item["elapsedMs"] for item in results if item["kind"] == kind)
        if times:
            by_kind[kind] = {"cases": len(times), "maxMs": times[-1]}
    return {
        "schema": "potongin.gate/1",
        "gate": "QG-SEC upload fuzz (plan §9.2, §10.2)",
        "task": "T3.1",
        "threshold": "100% rejected (4xx) or safely normalised (2xx) within the time cap "
                     "(image 20 s, audio 60 s); no 5xx",
        "cases": len(results),
        "rejected": counts.get("rejected", 0),
        "normalised": counts.get("normalised", 0),
        "serverErrors": counts.get("server_error", 0),
        "failed": sum(1 for item in results if not item["pass"]),
        "timesByKind": by_kind,
        "pass": all(item["pass"] for item in results) and bool(results),
        "results": results,
        **extra,
    }


# Python level: the Node transport rules, then edit_v2.assets.

_EXIT_STATUS = {0: 201, 4: 404, 9: 409}
_CODE_STATUS = {"asset_type_unsupported": 415, "asset_too_large": 413, "asset_rejected": 422,
                "asset_quota_exceeded": 409}


def quarantine(job_dir: Path, data: bytes) -> str:
    """Write ``data`` where the route streams an upload; returns its incoming id."""
    incoming = Path(job_dir) / "analysis" / "assets" / ".incoming"
    incoming.mkdir(parents=True, exist_ok=True, mode=0o700)
    incoming_id = str(uuid.uuid4())
    fd = os.open(incoming / incoming_id, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW,
                 0o600)
    with os.fdopen(fd, "wb") as handle:
        handle.write(data)
    return incoming_id


def run_ingest(corpus_dir: Path, *, jobs_root: Path, job_id: str,
               handle: Callable | None = None, only: Iterable[str] | None = None) -> list[dict]:
    """Every case through the transport rules of ``web/lib/asset-upload.mjs`` (mirrored with
    the shared Python helpers) and ``edit_v2.assets.handle`` in-process."""
    from ai_clipper.edit_v2 import assets

    handle = handle or assets.handle
    corpus_dir = Path(corpus_dir)
    job_dir = Path(jobs_root) / job_id
    (job_dir / "analysis").mkdir(parents=True, exist_ok=True)
    wanted = set(only) if only is not None else None
    results = []
    for case in load_index(corpus_dir)["cases"]:
        if wanted is not None and case["id"] not in wanted:
            continue
        data = (corpus_dir / case["file"]).read_bytes()
        started = time.monotonic()
        transport = _transport(assets, case, data)
        if transport is not None:
            status, code = transport
            results.append(verdict(case, status=status, code=code, stage="transport",
                                   elapsed_ms=round((time.monotonic() - started) * 1000)))
            continue
        incoming = job_dir / "analysis" / "assets" / ".incoming"
        incoming_id = quarantine(job_dir, data)
        envelope = {"op": "ingest", "jobId": job_id, "incomingId": incoming_id,
                    "kind": case["kind"], "mime": case["mime"],
                    "name": assets.normalise_name(case["name"]),
                    "idempotencyKey": str(uuid.uuid4())}
        exit_code, payload = handle(json.dumps(envelope).encode(), jobs_root=Path(jobs_root))
        elapsed = round((time.monotonic() - started) * 1000)
        error = payload.get("error") or {}
        status = _EXIT_STATUS.get(exit_code, 500)
        if exit_code == 3:
            status = _CODE_STATUS.get(error.get("code"), 500)
        stored = name = None
        if exit_code == 0:
            asset = payload["asset"]
            suffix = ".png" if asset["kind"] == "logo" else ".m4a"
            stored = (job_dir / "analysis" / "assets" / f"{asset['sha256']}{suffix}").read_bytes()
            name = asset["name"]
        results.append(verdict(case, status=status, code=error.get("code"), reason=error.get("ref"),
                               elapsed_ms=elapsed, stored=stored, name=name, stage="ingest"))
        if (incoming / incoming_id).exists():
            results[-1]["pass"] = False
            results[-1]["problems"].append("the quarantined original survived")
    return results


def _transport(assets, case: dict, data: bytes) -> tuple[int, str] | None:
    """The Node route's own refusals, in its order (web/lib/asset-upload.mjs)."""
    kind, mime = case["kind"], case["mime"]
    if mime not in assets.ALLOWED_TYPES.get(kind, ()):
        return 415, "asset_type_unsupported"
    if len(data) == 0:
        return 400, "invalid_request"
    if len(data) > assets.MAX_UPLOAD_BYTES[kind]:
        return 413, "asset_too_large"
    try:
        assets.normalise_name(case["name"])
    except ValueError:
        return 400, "invalid_request"
    if assets.sniff(data[:64]) != assets.FORMATS[mime]:
        return 415, "asset_type_unsupported"
    return None


# HTTP level.


def _login(base: str, username: str, password: str) -> str:
    body = urllib.parse.urlencode({"username": username, "password": password}).encode()
    request = urllib.request.Request(f"{base}/api/auth/login", data=body, method="POST", headers={
        "Content-Type": "application/x-www-form-urlencoded", "Origin": base,
        "Sec-Fetch-Site": "same-origin"})

    class NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *_args, **_kwargs):
            return None

    opener = urllib.request.build_opener(NoRedirect)
    try:
        response = opener.open(request, timeout=30)
        headers = response.headers
    except urllib.error.HTTPError as error:
        headers = error.headers
    for value in headers.get_all("Set-Cookie") or []:
        name, _, rest = value.partition("=")
        if name.strip() == "potongin_session":
            return rest.split(";", 1)[0]
    raise SystemExit("login failed")


def post_case(base: str, job_id: str, token: str, case: dict, data: bytes) -> tuple[int, dict]:
    """POST one case; an answer sent before the body was read (the connection then closes on
    the sender) is still read. Status 0 means no answer could be read (the case fails)."""
    headers = {"Origin": base, "Sec-Fetch-Site": "same-origin", "Cookie": f"potongin_session={token}",
               "Content-Type": case["mime"], "X-Asset-Kind": case["kind"],
               "Idempotency-Key": str(uuid.uuid4()), "Content-Length": str(len(data))}
    if case["name"] is not None:
        headers["X-Asset-Name"] = urllib.parse.quote(case["name"], safe="")
    parsed = urllib.parse.urlsplit(base)
    conn = http.client.HTTPConnection(parsed.hostname, parsed.port, timeout=180)
    try:
        conn.putrequest("POST", f"/api/jobs/{job_id}/assets", skip_accept_encoding=True)
        for name, value in headers.items():
            conn.putheader(name, value)
        conn.endheaders()
        view = memoryview(data)
        try:
            for start in range(0, len(view), 1 << 20):
                conn.send(view[start:start + (1 << 20)])
        except (BrokenPipeError, ConnectionResetError):
            pass  # answered early: the answer is read below
        try:
            response = conn.getresponse()
            raw = response.read()
        except (ConnectionError, http.client.HTTPException):
            return 0, {"code": "no_answer"}
        try:
            body = json.loads(raw or b"{}")
        except ValueError:
            body = {}
        if response.status == 429:  # the per-session upload rate: not this case's verdict
            body = {**body, "retryAfter": response.getheader("Retry-After")}
        return response.status, body
    finally:
        conn.close()


def fetch(base: str, path: str, token: str) -> bytes:
    request = urllib.request.Request(f"{base}{path}", headers={
        "Cookie": f"potongin_session={token}"})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def run_http(corpus_dir: Path, *, base: str, job_id: str, username: str,
             password: str) -> list[dict]:
    token = _login(base, username, password)
    corpus_dir = Path(corpus_dir)
    results = []
    for case in load_index(corpus_dir)["cases"]:
        data = (corpus_dir / case["file"]).read_bytes()
        for _attempt in range(20):  # 30 uploads per minute per session: wait and send again
            started = time.monotonic()
            status, body = post_case(base, job_id, token, case, data)
            elapsed = round((time.monotonic() - started) * 1000)
            if status != 429:
                break
            wait = body.get("retryAfter")
            time.sleep(int(wait) if isinstance(wait, str) and wait.isdigit() else 2)
        stored = None
        if 200 <= status < 300:
            stored = fetch(base, f"/api/jobs/{job_id}/assets/{body['sha256']}", token)
            if hashlib.sha256(stored).hexdigest() != body["sha256"]:
                status = 599  # the served bytes are not the asset: fail the case loudly
        results.append(verdict(case, status=status, code=body.get("code"),
                               reason=body.get("reason"), elapsed_ms=elapsed, stored=stored,
                               name=body.get("name"), stage="http"))
    return results


# Ingest timing (plan §11.3 T3.1): one ingest process per upload, as the route spawns it.

TIMING_LIMITS_MS = {"image": 2000, "track5min": 8000}
TIMING_RUNS = {"image": 10, "track5min": 5}


def percentile(values: Iterable[int], q: float) -> int:
    """The nearest-rank percentile of ``values`` (``q`` in (0, 1])."""
    ordered = sorted(values)
    if not ordered:
        raise ValueError("no samples")
    return ordered[max(1, math.ceil(q * len(ordered))) - 1]


def timing_report(runs: list[dict]) -> dict:
    """Per input and pooled per class; a class without samples fails the report."""
    inputs, pooled = [], {name: [] for name in TIMING_LIMITS_MS}
    for run in runs:
        samples = list(run["samplesMs"])
        pooled[run["class"]].extend(samples)
        inputs.append({**run, "runs": len(samples), "p50Ms": percentile(samples, 0.5),
                       "p95Ms": percentile(samples, 0.95), "maxMs": max(samples)})
    report: dict = {}
    for name, limit in TIMING_LIMITS_MS.items():
        samples = pooled[name]
        if not samples:
            report[name] = {"samples": 0, "limitMs": limit, "pass": False}
            continue
        p95 = percentile(samples, 0.95)
        report[name] = {"samples": len(samples), "p50Ms": percentile(samples, 0.5), "p95Ms": p95,
                        "maxMs": max(samples), "limitMs": limit, "pass": p95 <= limit}
    report["inputs"] = inputs
    report["pass"] = all(report[name]["pass"] for name in TIMING_LIMITS_MS)
    return report


def _orientation_app1(orientation: int) -> bytes:
    tiff = (b"II*\x00" + struct.pack("<IH", 8, 1)
            + struct.pack("<HHIHH", 0x0112, 3, 1, orientation, 0) + struct.pack("<I", 0))
    payload = b"Exif\x00\x00" + tiff
    return b"\xff\xe1" + struct.pack(">H", len(payload) + 2) + payload


def build_timing_inputs(out_dir: Path, *, ffmpeg: str | None = None,
                        track_seconds: int = 300) -> list[dict]:
    """Logos at the sizes clippers upload and 5-minute tracks in every format (generated)."""
    ffmpeg = ffmpeg or shutil.which("ffmpeg")
    if ffmpeg is None:
        raise SystemExit("ffmpeg is required to build the timing inputs")
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    inputs: list[dict] = []

    def add(label: str, file: str, kind: str, mime: str) -> None:
        inputs.append({"input": label, "file": file, "kind": kind, "mime": mime,
                       "class": "image" if kind == "logo" else "track5min",
                       "bytes": (out / file).stat().st_size})

    one = ["-frames:v", "1"]
    _ffmpeg(ffmpeg, "-f", "lavfi", "-i", "testsrc2=s=1024x1024,format=rgba", *one,
            str(out / "png-1024.png"))
    add("PNG 1024x1024 RGBA", "png-1024.png", "logo", "image/png")
    _ffmpeg(ffmpeg, "-f", "lavfi", "-i", "testsrc2=s=1600x1600,noise=alls=40:allf=t,format=rgba",
            *one, str(out / "png-1600-noisy.png"))
    add("PNG 1600x1600 RGBA noisy", "png-1600-noisy.png", "logo", "image/png")
    grain = "noise=alls=24:allf=t"  # photo-like entropy: several MB, as phone pictures are
    _ffmpeg(ffmpeg, "-f", "lavfi", "-i", f"testsrc2=s=4000x3000,{grain}", *one, "-q:v", "3",
            str(out / "plain-4000.jpg"))
    jpeg = (out / "plain-4000.jpg").read_bytes()
    (out / "jpeg-4000-exif6.jpg").write_bytes(jpeg[:2] + _orientation_app1(6) + jpeg[2:])
    (out / "plain-4000.jpg").unlink()
    add("JPEG 4000x3000 EXIF 6", "jpeg-4000-exif6.jpg", "logo", "image/jpeg")
    _ffmpeg(ffmpeg, "-f", "lavfi", "-i", f"testsrc2=s=4096x4096,{grain}", *one, "-q:v", "4",
            str(out / "jpeg-4096.jpg"))
    add("JPEG 4096x4096", "jpeg-4096.jpg", "logo", "image/jpeg")
    if _has_encoder(ffmpeg, "libwebp"):
        _ffmpeg(ffmpeg, "-f", "lavfi", "-i", f"testsrc2=s=3000x2000,{grain}", *one, "-c:v",
                "libwebp", "-quality", "80", str(out / "webp-3000.webp"))
        add("WebP 3000x2000", "webp-3000.webp", "logo", "image/webp")
        _ffmpeg(ffmpeg, "-f", "lavfi", "-i", "testsrc2=s=512x512,format=rgba", *one, "-c:v",
                "libwebp", "-lossless", "1", str(out / "webp-512-alpha.webp"))
        add("WebP 512x512 lossless alpha", "webp-512-alpha.webp", "logo", "image/webp")

    seconds = str(int(track_seconds))
    master = out / "master.wav"  # 44.1 kHz stereo: a tone over pink noise (over the cap itself)
    _ffmpeg(ffmpeg, "-f", "lavfi", "-i", f"sine=frequency=220:sample_rate=44100:duration={seconds}",
            "-f", "lavfi", "-i",
            f"anoisesrc=color=pink:amplitude=0.08:sample_rate=44100:duration={seconds}",
            "-filter_complex", "[0:a][1:a]amix=inputs=2:normalize=0,pan=stereo|c0=c0|c1=c0[a]",
            "-map", "[a]", "-c:a", "pcm_s16le", str(master))
    label = f"{int(track_seconds) // 60} min" if track_seconds >= 60 else f"{seconds} s"
    tracks = [("libmp3lame", f"MP3 320k 44.1k stereo {label}", "track.mp3", "audio/mpeg",
               ["-c:a", "libmp3lame", "-b:a", "320k"]),
              ("aac", f"M4A AAC 256k {label}", "track.m4a", "audio/mp4",
               ["-c:a", "aac", "-b:a", "256k"]),
              ("flac", f"FLAC 44.1k stereo {label}", "track.flac", "audio/flac", ["-c:a", "flac"]),
              ("libvorbis", f"Ogg Vorbis q6 {label}", "track.ogg", "audio/ogg",
               ["-c:a", "libvorbis", "-q:a", "6"]),
              ("pcm_s16le", f"WAV 48k mono {label}", "track.wav", "audio/wav",
               ["-ac", "1", "-ar", "48000", "-c:a", "pcm_s16le"])]
    for encoder, name, file, mime, codec in tracks:
        if encoder in ("libmp3lame", "libvorbis") and not _has_encoder(ffmpeg, encoder):
            continue
        _ffmpeg(ffmpeg, "-i", str(master), *codec, str(out / file))
        add(name, file, "music", mime)
    master.unlink()
    (out / "timing.json").write_text(json.dumps(inputs, indent=1) + "\n")
    return inputs


def run_timing(inputs_dir: Path, inputs: list[dict], *, jobs_root: Path,
               python: str = sys.executable, runs: dict | None = None,
               pythonpath: str | None = None) -> list[dict]:
    """Every input ingested ``runs[class]`` times by ``python -m ai_clipper.edit_v2.assets``
    (start-up, hashing, probe, normalise and store included); the stored asset is removed
    after each run so every run writes."""
    runs = runs or TIMING_RUNS
    job_id = str(uuid.uuid4())
    job_dir = Path(jobs_root) / job_id
    (job_dir / "analysis").mkdir(parents=True)
    env = {name: os.environ[name] for name in ("PATH", "HOME", "LANG", "TZ", "TMPDIR")
           if os.environ.get(name)}
    env["JOBS_ROOT"] = str(jobs_root)
    if pythonpath:
        env["PYTHONPATH"] = pythonpath
    results = []
    for item in inputs:
        data = (Path(inputs_dir) / item["file"]).read_bytes()
        samples, normalised = [], None
        for _ in range(runs[item["class"]]):
            envelope = {"op": "ingest", "jobId": job_id, "incomingId": quarantine(job_dir, data),
                        "kind": item["kind"], "mime": item["mime"], "name": None,
                        "idempotencyKey": str(uuid.uuid4())}
            started = time.monotonic()
            done = subprocess.run([python, "-m", "ai_clipper.edit_v2.assets"],
                                  input=json.dumps(envelope).encode(), capture_output=True,
                                  env=env, timeout=180, check=False)
            samples.append(round((time.monotonic() - started) * 1000))
            try:
                asset = json.loads(done.stdout)["asset"]
            except (ValueError, KeyError):
                raise SystemExit(f"{item['input']}: the ingest failed (exit {done.returncode})"
                                 ) from None
            normalised = {key: asset[key] for key in ("w", "h", "durationMs", "lufsC")}
            for stored in (job_dir / "analysis" / "assets").glob(f"{asset['sha256']}.*"):
                stored.unlink()
        results.append({"input": item["input"], "kind": item["kind"], "class": item["class"],
                        "bytes": len(data), "samplesMs": samples, "normalised": normalised})
    return results


# The child-environment audit (E11): wrappers on PATH record each child's environment.

FFMPEG_CHILD_ENV = ("PATH", "LANG", "LC_ALL", "HOME", "TMPDIR")  # edit_v2.assets.child_env


def child_env_allowlist(root: Path = ROOT) -> tuple[str, ...]:
    """``CHILD_ENV_ALLOWLIST`` of web/lib/python-cli.mjs: what the route's Python child gets."""
    text = (Path(root) / "web" / "lib" / "python-cli.mjs").read_text(encoding="utf-8")
    block = re.search(r"CHILD_ENV_ALLOWLIST = Object\.freeze\(\[(.*?)\]\)", text, re.DOTALL)
    if block is None:
        raise SystemExit("CHILD_ENV_ALLOWLIST not found in web/lib/python-cli.mjs")
    return tuple(re.findall(r'"([A-Z][A-Z0-9_]*)"', block.group(1)))


def recorder_script(*, real: str, tool: str, log: str, interpreter: str) -> str:
    """A wrapper that appends ``{tool, env}`` (its /proc/self/environ) to ``log`` and execs
    ``real`` with the same arguments."""
    return (f"#!{interpreter}\n"
            "import json, os, sys\n"
            "items = open('/proc/self/environ', 'rb').read().split(b'\\0')\n"
            "env = dict(i.decode('utf-8', 'replace').split('=', 1) for i in items if b'=' in i)\n"
            f"with open({log!r}, 'a', encoding='utf-8') as handle:\n"
            f"    handle.write(json.dumps({{'tool': {tool!r}, 'env': env}}) + '\\n')\n"
            f"os.execv({real!r}, [{real!r}, *sys.argv[1:]])\n")


def audit_environ(records: list[dict], *, allow: dict, marker: str) -> dict:
    """Names outside each tool's allowlist (names only) and values holding ``marker``."""
    outside, planted, by_tool = [], 0, {}
    for record in records:
        tool, env = record["tool"], record["env"]
        by_tool[tool] = by_tool.get(tool, 0) + 1
        for name, value in env.items():
            if name not in allow.get(tool, ()) and {"tool": tool, "name": name} not in outside:
                outside.append({"tool": tool, "name": name})
            planted += marker in value
    return {"children": len(records), "byTool": dict(sorted(by_tool.items())),
            "namesOutsideAllowlist": outside, "plantedValuesFound": planted,
            "pass": bool(records) and not outside and planted == 0}


def read_environ_log(path: Path) -> list[dict]:
    return [json.loads(line) for line in Path(path).read_text().splitlines() if line.strip()]


# The HTTP security matrix: authentication without the proxy, CSRF, transport headers, a body
# over 10 MB, the §9.2 serving headers.


def _send(base: str, method: str, path: str, *, headers: dict | None = None,
          body: bytes | None = None, chunked: bool = False) -> tuple[int, dict, bytes]:
    parsed = urllib.parse.urlsplit(base)
    conn = http.client.HTTPConnection(parsed.hostname, parsed.port, timeout=300)
    try:
        conn.putrequest(method, path, skip_accept_encoding=True)
        for name, value in (headers or {}).items():
            conn.putheader(name, value)
        if chunked:
            conn.putheader("Transfer-Encoding", "chunked")
        elif body is not None:
            conn.putheader("Content-Length", str(len(body)))
        conn.endheaders()
        try:
            if chunked and body is not None:
                conn.send(f"{len(body):x}\r\n".encode() + body + b"\r\n0\r\n\r\n")
            elif body is not None:
                view = memoryview(body)
                for start in range(0, len(view), 1 << 20):
                    conn.send(view[start:start + (1 << 20)])
        except (BrokenPipeError, ConnectionResetError):
            pass  # answered early: the answer is read below
        response = conn.getresponse()
        raw = response.read()
        return response.status, {k.lower(): v for k, v in response.getheaders()}, raw
    finally:
        conn.close()


def _code(raw: bytes) -> str | None:
    try:
        value = json.loads(raw or b"{}")
    except ValueError:
        return None
    return value.get("code") if isinstance(value, dict) else None


def tone_wav(seconds: int, rate: int = 48_000) -> bytes:
    """Mono s16 1 kHz at a quarter of full scale; one period repeated (48 samples at 48 kHz)."""
    period = rate // 1000
    cycle = array.array("h", (round(8192 * math.sin(2 * math.pi * n / period))
                              for n in range(period)))
    if sys.byteorder != "little":
        cycle.byteswap()
    data = cycle.tobytes() * (seconds * 1000)
    header = (b"RIFF" + struct.pack("<I", 36 + len(data)) + b"WAVEfmt "
              + struct.pack("<IHHIIHH", 16, 1, 1, rate, rate * 2, 2, 16)
              + b"data" + struct.pack("<I", len(data)))
    return header + data


def run_matrix(base: str, *, job_id: str, username: str, password: str,
               big_seconds: int = 420) -> dict:
    token = _login(base, username, password)
    session = f"potongin_session={token}"
    logo = _png([(b"IHDR", _ihdr(2, 2)), (b"IDAT", zlib.compress(b"\x00" + bytes(8) + b"\x00"
                                                                 + bytes(8))), (b"IEND", b"")])
    upload = f"/api/jobs/{job_id}/assets"

    def headers(**changes) -> dict:
        base_headers = {"Origin": base, "Sec-Fetch-Site": "same-origin", "Cookie": session,
                        "Content-Type": "image/png", "X-Asset-Kind": "logo",
                        "Idempotency-Key": str(uuid.uuid4())}
        base_headers.update({key.replace("_", "-"): value for key, value in changes.items()})
        return {key: value for key, value in base_headers.items() if value is not None}

    def post(path: str, body: bytes | None, head: dict, **options) -> tuple[int, dict, bytes]:
        for _attempt in range(20):  # the 30-per-minute upload rate of the session
            status, answer, raw = _send(base, "POST", path, headers=head, body=body, **options)
            if status != 429:
                return status, answer, raw
            wait = answer.get("retry-after", "2")
            time.sleep(int(wait) if wait.isdigit() else 2)
            head = {**head, "Idempotency-Key": str(uuid.uuid4())}
        return status, answer, raw

    matrix: list[dict] = []

    def check(case: str, expected: int, status: int, raw: bytes, **extra) -> None:
        matrix.append({"case": case, "expected": expected, "status": status, "code": _code(raw),
                       "pass": status == expected and all(extra.values()), **extra})

    for case, expected, path, head, options in [
        ("no session cookie (the route itself, no proxy in front)", 401, upload,
         headers(Cookie=None), {}),
        ("forged session cookie", 401, upload, headers(Cookie="potongin_session=e30.forged"), {}),
        ("no Origin", 403, upload, headers(Origin=None), {}),
        ("foreign Origin", 403, upload, headers(Origin="http://evil.example"), {}),
        ("Sec-Fetch-Site cross-site", 403, upload, headers(Sec_Fetch_Site="cross-site"), {}),
        ("malformed job id", 400, "/api/jobs/not-a-job/assets", headers(), {}),
        ("unknown job", 404, f"/api/jobs/{uuid.uuid4()}/assets", headers(), {}),
        ("chunked body without Content-Length", 411, upload, headers(), {"chunked": True}),
        ("no Idempotency-Key", 400, upload, headers(Idempotency_Key=None), {}),
        ("unknown X-Asset-Kind", 400, upload, headers(X_Asset_Kind="video"), {}),
        ("image/svg+xml for a logo", 415, upload, headers(Content_Type="image/svg+xml"), {}),
        ("SVG bytes declared as PNG", 415, upload, headers(), {"body": _svg()}),
    ]:
        status, _answer, raw = post(path, options.pop("body", logo), head, **options)
        check(case, expected, status, raw)
    status, _answer, raw = post(upload, logo + bytes((10 << 20) + 1 - len(logo)), headers())
    check("a logo one byte over 10 MB", 413, status, raw)

    status, _answer, raw = post(upload, logo, headers(X_Asset_Name=urllib.parse.quote("../Logo Toko.png")))
    check("a valid PNG logo", 201, status, raw)
    asset = json.loads(raw) if status == 201 else {}
    served = f"/api/jobs/{job_id}/assets/{asset.get('sha256', '0' * 64)}"
    status, answer, raw = _send(base, "GET", served)
    check("GET without a session stops at the proxy", 401, status, raw)
    status, answer, raw = _send(base, "GET", served, headers={"Cookie": session})
    check("GET serves the normalised logo with the §9.2 headers", 200, status, raw,
          sha256Matches=hashlib.sha256(raw).hexdigest() == asset.get("sha256"),
          contentType=answer.get("content-type") == "image/png",
          nosniff=answer.get("x-content-type-options") == "nosniff",
          csp=answer.get("content-security-policy") == "default-src 'none'; sandbox",
          corp=answer.get("cross-origin-resource-policy") == "same-origin",
          disposition=answer.get("content-disposition") == 'inline; filename="asset.png"',
          ranges=answer.get("accept-ranges") == "bytes",
          nameIsDisplayOnly=asset.get("name") == "Logo Toko.png")
    status, answer, raw = _send(base, "GET", served, headers={"Cookie": session,
                                                              "Range": "bytes=0-15"})
    check("GET with Range", 206, status, raw, length=len(raw) == 16,
          contentRange=answer.get("content-range", "").startswith("bytes 0-15/"))
    status, answer, raw = _send(base, "GET", f"{served}?part=nope", headers={"Cookie": session})
    check("GET with an unknown part", 400, status, raw)

    wav = tone_wav(big_seconds)
    started = time.monotonic()
    status, _answer, raw = post(upload, wav, headers(Content_Type="audio/wav", X_Asset_Kind="music"))
    elapsed = round((time.monotonic() - started) * 1000)
    music = json.loads(raw) if status == 201 else {}
    whole = abs(music.get("durationMs", 0) - big_seconds * 1000) <= 50
    check(f"a {len(wav) / 1e6:.1f} MB WAV arrives whole (no 10 MB proxy buffer)", 201, status, raw,
          wholeBody=whole)
    matrix[-1].update({"bytes": len(wav), "durationMs": music.get("durationMs"),
                       "elapsedMs": elapsed})
    peaks = f"/api/jobs/{job_id}/assets/{music.get('sha256', '0' * 64)}?part=peaks"
    status, answer, raw = _send(base, "GET", peaks, headers={"Cookie": session})
    check("GET ?part=peaks serves the music waveform", 200, status, raw,
          length=len(raw) == 2 * -(-music.get("durationMs", 0) // 10))
    return {"matrix": matrix, "pass": all(item["pass"] for item in matrix)}


# CLI.


def _toolchain() -> dict:
    ffmpeg = shutil.which("ffmpeg")
    version = "missing"
    if ffmpeg:
        version = subprocess.run([ffmpeg, "-version"], capture_output=True, text=True,
                                 check=False).stdout.split("\n", 1)[0]
    return {"ffmpeg": version, "python": platform.python_version(),
            "machine": platform.machine(), "cpus": os.cpu_count(),
            "load": [round(x, 1) for x in os.getloadavg()]}


def _write(path: Path, report: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, indent=1, ensure_ascii=False) + "\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    sub = parser.add_subparsers(dest="command", required=True)
    write = sub.add_parser("write")
    write.add_argument("out_dir", type=Path)
    ingest = sub.add_parser("ingest")
    ingest.add_argument("corpus", type=Path)
    ingest.add_argument("evidence", type=Path)
    ingest.add_argument("--jobs-root", type=Path)
    http = sub.add_parser("http")
    http.add_argument("corpus", type=Path)
    http.add_argument("evidence", type=Path)
    http.add_argument("--base", required=True)
    http.add_argument("--job", required=True)
    http.add_argument("--stack", default="")
    matrix = sub.add_parser("matrix")
    matrix.add_argument("evidence", type=Path)
    matrix.add_argument("--base", required=True)
    matrix.add_argument("--job", required=True)
    matrix.add_argument("--environ-log", type=Path)
    matrix.add_argument("--marker", default="planted-secret")
    matrix.add_argument("--stack", default="")
    recorders = sub.add_parser("recorders")
    recorders.add_argument("out_dir", type=Path)
    recorders.add_argument("--log", required=True)
    recorders.add_argument("--interpreter", required=True)
    recorders.add_argument("--python", required=True)
    recorders.add_argument("--ffmpeg", default="/usr/bin/ffmpeg")
    recorders.add_argument("--ffprobe", default="/usr/bin/ffprobe")
    inputs = sub.add_parser("timing-inputs")
    inputs.add_argument("out_dir", type=Path)
    inputs.add_argument("--track-seconds", type=int, default=300)
    timing = sub.add_parser("timing")
    timing.add_argument("inputs", type=Path)
    timing.add_argument("evidence", type=Path)
    timing.add_argument("--python", default=sys.executable)
    timing.add_argument("--pythonpath")
    timing.add_argument("--stack", default="")
    args = parser.parse_args(argv)
    if args.command == "write":
        index = build_corpus(args.out_dir)
        print(json.dumps({"cases": len(index["cases"]), "dir": str(args.out_dir)}))
        return 0
    if args.command == "recorders":
        args.out_dir.mkdir(parents=True, exist_ok=True)
        for tool, real in (("python", args.python), ("ffmpeg", args.ffmpeg),
                           ("ffprobe", args.ffprobe)):
            wrapper = args.out_dir / tool
            wrapper.write_text(recorder_script(real=real, tool=tool, log=args.log,
                                               interpreter=args.interpreter))
            wrapper.chmod(0o755)
        return 0
    if args.command == "timing-inputs":
        found = build_timing_inputs(args.out_dir, track_seconds=args.track_seconds)
        print(json.dumps({"inputs": len(found), "dir": str(args.out_dir)}))
        return 0
    if args.command == "timing":
        listed = json.loads((args.inputs / "timing.json").read_text())
        with tempfile.TemporaryDirectory(prefix="upload-timing-jobs-") as tmp:
            runs = run_timing(args.inputs, listed, jobs_root=Path(tmp), python=args.python,
                              pythonpath=args.pythonpath)
        report = {"schema": "potongin.gate/1", "task": "T3.1",
                  "gate": "ingest p95 (plan §11.3 T3.1): <= 2 s per image, <= 8 s per 5-minute "
                          "track",
                  "method": "python -m ai_clipper.edit_v2.assets ingest, one process per upload "
                            "as the route spawns it (start-up, hashing, probe, normalise, store); "
                            "the stored asset removed after each run so every run writes",
                  **timing_report(runs), "stack": args.stack, "toolchain": _toolchain()}
        _write(args.evidence, report)
        print(json.dumps({key: report[key] for key in ("image", "track5min", "pass")}))
        return 0 if report["pass"] else 1
    if args.command == "matrix":
        username, password = os.environ.get("APP_USERNAME"), os.environ.get("APP_PASSWORD")
        if not username or not password:
            raise SystemExit("APP_USERNAME and APP_PASSWORD of the test server are required")
        report = {"schema": "potongin.gate/1", "task": "T3.1",
                  "gate": "QG-SEC on the real server: the upload route authenticates itself "
                          "without the proxy, a body over 10 MB arrives whole, the §9.2 serving "
                          "headers, and no secret in any child the server spawned (E11)",
                  **run_matrix(args.base.rstrip("/"), job_id=args.job, username=username,
                               password=password)}
        if args.environ_log is not None:
            from ai_clipper.edit_v2 import assets

            allow = {"python": set(child_env_allowlist()),
                     "ffmpeg": set(assets.child_env(Path("/x"))),
                     "ffprobe": set(assets.child_env(Path("/x")))}
            audit = audit_environ(read_environ_log(args.environ_log), allow=allow,
                                  marker=args.marker)
            report["environAudit"] = {**audit, "allowlists": {k: sorted(v) for k, v in
                                                                allow.items()}}
            report["pass"] = report["pass"] and audit["pass"]
        report.update(stack=args.stack, toolchain=_toolchain())
        _write(args.evidence, report)
        print(json.dumps({"checks": len(report["matrix"]), "pass": report["pass"],
                          "environ": report.get("environAudit", {}).get("children")}))
        return 0 if report["pass"] else 1
    if args.command == "ingest":
        with tempfile.TemporaryDirectory(prefix="upload-fuzz-jobs-") as tmp:
            root = args.jobs_root or Path(tmp)
            results = run_ingest(args.corpus, jobs_root=root, job_id=str(uuid.uuid4()))
        report = summarise(results, level="python (transport rules + edit_v2.assets.handle)",
                           toolchain=_toolchain())
    else:
        username, password = os.environ.get("APP_USERNAME"), os.environ.get("APP_PASSWORD")
        if not username or not password:
            raise SystemExit("APP_USERNAME and APP_PASSWORD of the test server are required")
        results = run_http(args.corpus, base=args.base.rstrip("/"), job_id=args.job,
                           username=username, password=password)
        report = summarise(results, level="http (POST /api/jobs/:id/assets, next start)",
                           stack=args.stack, toolchain=_toolchain())
    _write(args.evidence, report)
    print(json.dumps({key: report[key] for key in ("cases", "rejected", "normalised",
                                                     "serverErrors", "failed", "pass")}))
    return 0 if report["pass"] else 1


if __name__ == "__main__":
    sys.exit(main())
